### ISSUE TITLE
Opening Docker

### ISSUE THREAD

**Issue by sidneyML** [nus-cs2030/2223-s2#10]
When I tried to open docker and I got a popup saying Environment error "We are sorry, but your hardware is incompatible with Docker Desktop." How do I proceed?

**Comment by sp4ce-cowboy** [comment]
If you are using a mac with Apple Silicon ( > About This Mac > M1/M2 Processor) then you have to install from the Apple Chip specific download ([Docker](https://www.docker.com/products/docker-desktop/) > "Apple Chip"), the Intel one would throw a hardware incompatibility error. (Assuming you haven't done this already, otherwise I'm not too sure.)

**Comment by sidneyML** [comment]
omg thank you so much
