### ISSUE TITLE
Lab 3: Possible Violation of design requirements

### ISSUE THREAD

**Issue by JYeoZS** [nus-cs2030/2223-s2#102]
## Description:

Hi, received this problem when submitting lab 3. Code output works fine on laptop. Not sure what the violation is?

Thanks.

## Screenshots
![Violation Lab 3](https://user-images.githubusercontent.com/122290983/218246032-347c84b5-d928-4525-8633-b41b7e03ba48.jpg)

Screenshots (if any)

**Comment by maze508** [comment]
Does your design happen to go against any of these guidelines?

Make use of polymorphism instead of checking the type of event in the simulator class:
- Your event class should have a method that returns another type of event. If you need to return more values, consider putting into a pair.
- Each event will transit into the next event, e.g. a serve will transit to a done event after running the method above.
- Terminating events (done and leave) can return itself since there is no event to transit to.

**Comment by territxl** [comment]
I think you can check if there are any cyclical dependencies amongst your different events (i.e. ur events should return another type of event for polymorphism)

**Comment by SimonSeeYongsheng** [comment]
Did you use any instanceof operator or getclass method? It is banned on codecrunch.

**Comment by JYeoZS** [comment]
Hi @maze508 almost spot on. There is need for Event classes and polymorphic behaviour.

So if lab 2 does not follow these requirements, there's need to redo lab 2 + 3 again.

Cheers to all!
