### ISSUE TITLE
Child class constructor for SmallCruise exercise 2

### ISSUE THREAD

**Issue by yuzujy** [nus-cs2030/2223-s2#115]
Hi, can i ask if the child class have less arguments in its constructor compared to the parent class? also how do i assign super.serviceTime = 30 and super.n = 1 where super.n is the number of loaders required as attributes need to be set final. thanks!

<img width="691" alt="Screenshot 2023-02-12 180735" src="https://user-images.githubusercontent.com/122694072/218304901-c35501e1-c824-4f13-8d26-a8ce6e17be74.png">

**Comment by weitatftw** [comment]
I don't think that a child class can have fewer arguments in the constructor compared to the parent class as it will throw an error. You can try using the parent constructor and pass the necessary arguments, including super.serviceTime and super.n values to it in order to set the values of the attributes to the desired values

**Comment by trwstin** [comment]
> also how do i assign super.serviceTime = 30 and super.n = 1 where super.n is the number of loaders required as attributes need to be set final.
You can do this directly in the constructor, it should be within the super(.....).

**Comment by Cfyjdfk** [comment]
Intialising the super class' variables will already be done in the its own constructor. 

```
class Cruise {
    private final int id;

    Cruise(int id) {
        this.id = id;
    }
}

class SmallCruise extends Cruise {
   SmallCruise(int id) {
       // super() calls the Cruise's constructor and assigns this.id to id alrady
       super(id);
   }
}
```

**Comment by yuzujy** [comment]
ok got it! thanks everyone
