### ISSUE TITLE
Lab 3 test case 5

### ISSUE THREAD

**Issue by yuzujy** [nus-cs2030/2223-s2#149]
hi somehow my code assumes that service time is always 1.00. However, i followed codecrunch for the DefaultServiceTime?

<img width="932" alt="image" src="https://user-images.githubusercontent.com/122694072/219438787-9e08c688-0bc7-426b-8dc1-e1164859312c.png">
<img width="908" alt="image" src="https://user-images.githubusercontent.com/122694072/219439727-f1a1890d-f13e-44f7-8001-52f944080bb1.png">

also in my simulator code i had:
DefaultServiceTime serviceTime = new DefaultServiceTime()

and when creating a customer i used:
serviceTime from the above code as one of the arguments.

can i ask how to solve this problem

**Comment by trwstin** [comment]
Perhaps try taking the CodeCrunch example as reference:

![image](https://user-images.githubusercontent.com/68576751/219444473-5c61cf7a-6c6a-4a5a-ae5e-9b827f1cc678.png)

The serviceTime attribute in your Simulator/Customer classes should be a Supplier<Double>, not a DefaultServiceTime object.

If you directly pass in DefaultServiceTime, then the values won't change when the Supplier changes - which I think is the issue here.

**Comment by SimonSeeYongsheng** [comment]
It should be Supplier<Double> instead of DefaultServiceTime
