### ISSUE TITLE
problem with test case 6

### ISSUE THREAD

**Issue by Delocy** [nus-cs2030/2223-s2#166]
# Summary

Description of the question / problem here.

## Description:
Anyone got this error too?
got this problem but i checked my comparator and it looks correct...
Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots
<img width="473" alt="Screenshot 2023-02-18 at 12 38 44 PM" src="https://user-images.githubusercontent.com/94375191/219836583-735f28c7-121d-454d-81ec-662d90e1f2fe.png">

Screenshots (if any)

**Comment by stxe09** [comment]
![Screenshot_20230220_111339](https://user-images.githubusercontent.com/122586851/220143728-855e968c-9bf1-4f7e-bebd-64cd3a9d0b29.png)

I'm having a similar issue for Lab 3 Test Case 5... but I doubt that my comparator has issues since the rest of the test cases was ok

lmk if you managed to identify ur problem?
