### ISSUE TITLE
Weird interaction

### ISSUE THREAD

**Issue by trickypepe** [nus-cs2030/2223-s2#186]
Code didn't work as intended (Error screenshot) when I used this.cost in compareTo method (Code screenshot). However, it worked after using this.getCost() instead which returns this.cost anyway. Any reasons why this may be the case?

![Error](https://user-images.githubusercontent.com/122513341/219957801-d59bf4f2-8454-45ae-a223-e41abe69231f.png)
![Code](https://user-images.githubusercontent.com/122513341/219957810-1de420ea-56db-43d0-a0b8-4258cf9d3502.png)

**Comment by jaejayrome** [comment]
This might be due to the fact that the "this" or "other" instance being compared to is a child instance of the Booking Class wherein the cost is declared as "private final", hence the child instance would not be able to access the cost property as a result since "private" modifier forbids it. Hope this helps.
