### ISSUE TITLE
general : unable to compile jsh file 

### ISSUE THREAD

**Issue by ouhznay** [nus-cs2030/2223-s2#189]
hi, i cant seem to compile my jsh file in the terminal and when i try to run the methods in my jsh file on my terminal, the error "cannot find symbol" kept popping out. I have checked the spelling and capitalisation of my method and also opened all the required files before running my .jsh file, it has no issue. I would really appreciate it if anyone can advice on how to fix the issue. thank you!

**Comment by sethteo** [comment]
You do not need/cant compile a jsh file , just run the file in jshell by calling /open name of file.jsh :)

**Comment by hengbl** [comment]
If JShell is displaying "cannot find symbol" and you are sure that you have opened all the files then most likely it is because you are not opening them in the top down dependency order. You should always open the file with the parent or the more "general" class first. The jsh file should definitely be opened last!

**Comment by huwenjie912** [comment]
yes yes make sure to open the parent classes first, i faced this problem too but once the order is correct all should be good

**Comment by SimonSeeYongsheng** [comment]
Make sure to push in all the dependent classes first

**Comment by AmanDesai34** [comment]
Ensure all the classes are opened in the correct order and then it should work!

**Comment by Klowhe** [comment]
https://docs.oracle.com/javase/10/jshell/toc.htm -> this might be helpful!
