### ISSUE TITLE
Exercise 2 issue

### ISSUE THREAD

**Issue by normantan1** [nus-cs2030/2223-s2#195]
![image](https://user-images.githubusercontent.com/88649714/220039656-c9e30bac-7bcd-4d9f-a518-8a1b6d58a6a2.png)
 
 What does the magic number means?

**Comment by slimzaza** [comment]
I think codecrunch does not  allow for undeclared numbers , so maybe you should just declare them as private static final above the constructor for magic numbers.

**Comment by AmanDesai34** [comment]
Yea an example would be you would have to declare them as private static final int forty = 40; and use forty in your code

**Comment by kyledilao777** [comment]
The reason why checkstyle penalises magic number because it forces your code to be more dynamic. Meaning if you were to change the variable which you assigned to 30 to let's say 50, you don't have to plow through your code to find out where you had 50. You just need to change the variable in your declaration. Hope this helps!

**Comment by normantan1** [comment]
Thanks guys appreciate the help!
