### ISSUE TITLE
Fixing Lab 2 Implementation Done/Leave Events

### ISSUE THREAD

**Issue by tali-a** [nus-cs2030/2223-s2#197]
Hi,  confused about what the terminating events (Done/Leave) return - in my simulator class, after executing an event, the event is directly added into the eventQueue. if the Done/Leave events return themselves, then they're continually being added into the event queue ?  Is it wrong to implement it this way? am also not sure if it’s other parts of my code causing the error.  thanks!

**Comment by trwstin** [comment]
If your execute method returns an event, then you'll have to find a way to return nothing (without using null) for Done and Leave.

Alternatively, your execute method can take in the poll'ed PQ and do the adding of events within the execute method instead of your Simulator class. 

This way, for your Done and Leave events you can return the PQ (which will no longer have the Done/Leave event due to how poll works) without creating a continuous cycle of removing and adding terminating events.

**Comment by sethteo** [comment]
You can use a boolean which returns true for your done and leave events but false for your other events and have your add back to queue method within an if statement which checks for the said boolean

**Comment by tali-a** [comment]
Thanks !
