### ISSUE TITLE
Test Case 10 - Too many service times generated.

### ISSUE THREAD

**Issue by pehzerong** [nus-cs2030/2223-s2#201]
Facing Too many service times generated issue. 

I am calling getServiceTime() under my Serve event only and I have checked the number of times it gets called for the available test cases and they all correspond to the number of Customers served. The issue only comes up for Test Case #10. Would appreciate any advice! Thanks!

**Comment by VanyaPriscillia** [comment]
I think you should recheck if there's something you haven't updated (maybe in your Serve class).

**Comment by sethteo** [comment]
For the last test case they are testing the fringe case where there is a queue size of more than 1 with multiple servers

**Comment by jchew03** [comment]
I had the same issue as you and my number of times getServiceTime() was called was the same as the number of served customers. For me the issue was that in my Wait class I did not handle the cases when there was more than 1 queue size correctly so your issue may be in your Wait class or Serve class and not your calling of getServiceTime().

**Comment by xyxyiuxy** [comment]
I only call it under ServeEvent, you can use System.out.println to check how many times you called it. The num of times should equal to the number of ppl served. And also this prob may be resulted from your simulator, for me I called execute twice in order to get my server list and next event, but execute() can only be called once.

**Comment by e0968868** [comment]
You can try to ensure that you only call getServiceTime() when the customer is actually getting served, maybe check if you are calling it in more than 1 location? Print statements would help

**Comment by pehzerong** [comment]
> I had the same issue as you and my number of times getServiceTime() was called was the same as the number of served customers. For me the issue was that in my Wait class I did not handle the cases when there was more than 1 queue size correctly so your issue may be in your Wait class or Serve class and not your calling of getServiceTime().

Hi, do you mind explaining what you meant by "more than 1 queue size"? Thanks!
