### ISSUE TITLE
Lab 3 - Managing Queue

### ISSUE THREAD

**Issue by displeasedcat** [nus-cs2030/2223-s2#205]
Hi, do you have any ideas how to manage the server queue for Lab 3? I'm currently trying an ImList of Customers for each Server but I am facing issues with cyclic dependency.

**Comment by sethteo** [comment]
You can make it an int attribute in your server class and have it ++ / -- whenever you serve/have a customer waiting and return a new server with all the same attributes except the changed int

**Comment by xyxyiuxy** [comment]
To avoid cyclic dependency, you should make sure the flow of your events is only in one direction. eg Arrive --- Serve ---- Done or Arrive --- Wait ---- Serve ---- Done. I also put an Imlist of customers in Server class to keep tract of which server serves which customer.

**Comment by coderlimjingcheng** [comment]
I also put my ImList of customer in server, but I did not face any cyclic dependency. One potential reason is that your Customer class depends on the Server class. For example, you have an attribute in your Customer class that states "private final Server" or you have a method that requires a Server, e.g. serveBy(Server). In that case, I would recommend you to re-design your customer class to one where it does not depend on Server, so that you can use ImList of Customer in your Server class.

**Comment by displeasedcat** [comment]
My cyclic dependency is coming from my Events: if there is still a customer in the queue, my Serve calls another Wait that will call Serve

Still figuring out how to deal with my Wait event when there is more than one person in the queue

**Comment by displeasedcat** [comment]
Thanks for all the advice! I managed to restructure my code and solve the issue
