### ISSUE TITLE
Too Many service times generated

### ISSUE THREAD

**Issue by eunice0361** [nus-cs2030/2223-s2#212]
I keep getting the error although my test cases are all correct when testing in my terminal..

![Screenshot 2023-02-22 at 3 12 00 AM](https://user-images.githubusercontent.com/111417317/220437969-d9bc810b-0a0e-4c80-a4c2-def47e7a7b61.png)

**Comment by Cepheux** [comment]
the best way to ensure the right amount of service times generated is to on call getServiceTime at the very last minute (i.e. when the customer has arrived and there is a spot in the serverqueue for the customer to wait/get served)

**Comment by granolaluvr69** [comment]
Hi, you could use println statements in your getServiceTime method to determine how many times service times are generated, and figure out where the method is called in your serve event by tracing the code. Hope it helps.

**Comment by meljwang** [comment]
I faced this issue even though I only called getServiceTime() in the Serve Event too. I later realised that I did not update the state of the servers in the Wait & Buffer Event properly which resulted in this error. Hope it helps!

**Comment by pehzerong** [comment]
I had this issues for a few days and managed to debug it after a long time. One or more of the following may be the reason for the bug:

1. calling getServiceTime() more than required. To check this, try putting a System.out.println() statement each time it gets invoked. Using the publicly available test cases, the number of time the method gets called should tally with the number of customers served.

2. Not updating the state of servers like what @meljwang mentioned. This was causing my issue because I did not update my state of servers in the various events. Depending on your code, I solved this by replacing the current server attached to the events with the latest version. 

Hope this helps!

**Comment by keshialimm** [comment]
> I had this issue for a few days and managed to debug it after a long time. One or more of the following may be the reason for the bug:
> 
> 1. calling getServiceTime() more than required. To check this, try putting a System.out.println() statement each time it gets invoked. Using the publicly available test cases, the number of time the method gets called should tally with the number of customers served.
> 2. Not updating the state of servers like what @meljwang mentioned. This was causing my issue because I did not update my state of servers in the various events. Depending on your code, I solved this by replacing the current server attached to the events with the latest version.
> 
> Hope this helps!

Currently my issue is the first one u mentioned, can I check how I can go about with avoiding calling getServiceTime() so many times? should I be assigning it to a variable in the customer class?

**Comment by granolaluvr69** [comment]
Remember how one of the tips given on codecrunch said to return a pair if you needed to return more than one value? That's how you're going to solve the problem of calling getServiceTime() more than once.

**Comment by meljwang** [comment]
> > I had this issue for a few days and managed to debug it after a long time. One or more of the following may be the reason for the bug:
> > 
> > 1. calling getServiceTime() more than required. To check this, try putting a System.out.println() statement each time it gets invoked. Using the publicly available test cases, the number of time the method gets called should tally with the number of customers served.
> > 2. Not updating the state of servers like what @meljwang mentioned. This was causing my issue because I did not update my state of servers in the various events. Depending on your code, I solved this by replacing the current server attached to the events with the latest version.
> > 
> > Hope this helps!
> 
> Currently my issue is the first one u mentioned, can I check how I can go about with avoiding calling getServiceTime() so many times? should I be assigning it to a variable in the customer class?

getServiceTime() should be defined in the Customer class, but only called in the Serve Event when a customer is being served. If the customer leaves after the arrival event, then there should not be a service time generated for that customer.

**Comment by pehzerong** [comment]
> > I had this issue for a few days and managed to debug it after a long time. One or more of the following may be the reason for the bug:
> > 
> > 1. calling getServiceTime() more than required. To check this, try putting a System.out.println() statement each time it gets invoked. Using the publicly available test cases, the number of time the method gets called should tally with the number of customers served.
> > 2. Not updating the state of servers like what @meljwang mentioned. This was causing my issue because I did not update my state of servers in the various events. Depending on your code, I solved this by replacing the current server attached to the events with the latest version.
> > 
> > Hope this helps!
> 
> Currently my issue is the first one u mentioned, can I check how I can go about with avoiding calling getServiceTime() so many times? should I be assigning it to a variable in the customer class?

The way I did it was to call getServiceTime() only in the Serve event, because then only customers who are served will have the method invoked. Customers who are not served would not have a serve event, and would not have their getServiceTime() called.

**Comment by yinshuennn** [comment]
> I faced this issue even though I only called getServiceTime() in the Serve Event too. I later realised that I did not update the state of the servers in the Wait & Buffer Event properly which resulted in this error. Hope it helps!

May I ask how do we update the state of servers in the Buffer Event without calling the getServiceTime()? Now when I replace the current server with the latest version, I'm not sure how else to get the new service time of the server other than calling the getServiceTime() of the customer the server is serving next.

**Comment by keshialimm** [comment]
> I faced this issue even though I only called getServiceTime() in the Serve Event too. I later realised that I did not update the state of the servers in the Wait & Buffer Event properly which resulted in this error. Hope it helps!

Hmm can I check what you mean by not updating state of servers properly? Now im just replacing the server with the new timing/ queue it has

**Comment by meljwang** [comment]
> > I faced this issue even though I only called getServiceTime() in the Serve Event too. I later realised that I did not update the state of the servers in the Wait & Buffer Event properly which resulted in this error. Hope it helps!
> 
> May I ask how do we update the state of servers in the Buffer Event without calling the getServiceTime()? Now when I replace the current server with the latest version, I'm not sure how else to get the new service time of the server other than calling the getServiceTime() of the customer the server is serving next.

What I did was to use a getter in Serve class to get the Server's nextAvailableTime and pass this value into the creation of new Buffer Event (if that customer is not at the front of the server queue) or Serve Event (if that customer is at the front of the server queue). Im not sure how to do it without using getter since getServiceTime() can only be called in the Serve Event.

**Comment by meljwang** [comment]
> > I faced this issue even though I only called getServiceTime() in the Serve Event too. I later realised that I did not update the state of the servers in the Wait & Buffer Event properly which resulted in this error. Hope it helps!
> 
> Hmm can I check what you mean by not updating state of servers properly? Now im just replacing the server with the new timing/ queue it has

I used the "this.server" attached to the Wait and Buffer Event at first which was not right. You should be using the servers from the ImList of currentStateOfServers (which should be updated after every event).

**Comment by wmingchuan** [comment]
Make sure your server's next available timings are updated each Serve event. When the Server is full and got queue space, Customer will be directed to the Wait event, add the Customer to the queue and let Wait event return a Check event. During the Check event, check if the Customer is the first in queue. If it is, return Serve event with the next available timing. If it is not, return another Check event with the next available timing so you can Check again. Make sure to update the queue in the Serve event.

**Comment by rayray39** [comment]
> Make sure your server's next available timings are updated each Serve event. When the Server is full and got queue space, Customer will be directed to the Wait event, add the Customer to the queue and let Wait event return a Check event. During the Check event, check if the Customer is the first in queue. If it is, return Serve event with the next available timing. If it is not, return another Check event with the next available timing so you can Check again. Make sure to update the queue in the Serve event.

Hi what do you mean by returning a new Check event with the next available timing? if the customer is not the first in queue, shouldnt it remain the same and not have anything done to it?

**Comment by wmingchuan** [comment]
> > Make sure your server's next available timings are updated each Serve event. When the Server is full and got queue space, Customer will be directed to the Wait event, add the Customer to the queue and let Wait event return a Check event. During the Check event, check if the Customer is the first in queue. If it is, return Serve event with the next available timing. If it is not, return another Check event with the next available timing so you can Check again. Make sure to update the queue in the Serve event.
> 
> Hi what do you mean by returning a new Check event with the next available timing? if the customer is not the first in queue, shouldnt it remain the same and not have anything done to it?

If you don't return another Check event and add it into the PQ, then you will never come back to that customer again. So what I did is:
If I have Customer 1, 2 and 3 in the queue and the server's next available timing is 1.00, I will have Check C1, Check C2 and Check C3 all lined up at 1.00 in the PQ. 
I run Check C1 first since it is at the front of the PQ. C1 is first in queue, I will return a Serve C1 at 1.00. Serve C1 will now be added to the front of the PQ since it has a smaller customerNumber. So I will run Serve C1 now. 
When I run Serve C1, I will update the Server's next available timing, for example to 2.00. I will remove C1 from the queue and return a Done event at 2.00 for C1.
After that the next event in the PQ will be Check C2. C2 will now be at the front of the queue since C1 is being served now. So I will return Serve C2 at the next available timing, which is 2.00.
After that I will run Check C3. But since C3 is not at the front of the queue, I will return another Check C3 at 2.00.

So fast forward to 2.00 now. Looking at the PQ, Done C1 will run first, followed by Serve C2. Serve C2 will update the next available timing, remove C2 from the queue and return Done C2. Then I will run Check C3 and realise that C3 is at front of the queue. So I return Serve C3 at the next available timing. If there are more Customers that joined the queue, they will all return Check Customer X at the next available timing, so we will come back to them again later to see if they are at the front of the queue or not and decide what to do.

**Comment by Cecilia0327** [comment]
> available

Could I ask how u override toString() method in Check event?

**Comment by wmingchuan** [comment]
> > available
> 
> Could I ask how u override toString() method in Check event?

just return ""

**Comment by ryantangmj** [comment]
this is because you called getServiceTime() more than once for each customer
