### ISSUE TITLE
lab 3 test case 7

### ISSUE THREAD

**Issue by xj8423** [nus-cs2030/2223-s2#223]
hi everyone, my service time generated for these customers are all mixed up :'( 
i put getServiceTime() only at one class, the Arrival Class (initially put it in the serve class but then the service times will be generated according to which customers get served first. i changed it to be in Arrival class so service times will be generated chronologically) 

im not sure if the problem is with my getServiceTime() ? since it passed all test cases from 1 to 6

any help will be greatly appreciated :') 

<img width="581" alt="Screenshot 2023-02-23 at 1 02 01 AM" src="https://user-images.githubusercontent.com/122519244/220702296-509ce573-00d5-4158-8601-7e4031d40b49.png">

**Comment by ringleading** [comment]
do ensure that you're not assuming the service times of the customers when handling the wait events, and that your server's available time is handled properly, see #219

**Comment by trwstin** [comment]
So you assign a customer with a service time as soon as they arrive? If so, then that is incorrect - we should only get their service time at the point of service.

If you assign it when they arrive, imagine this scenario:
1. Both Servers 1 and 2 are busy serving other customers.
2. Customer A arrives first, waits at server 1. He gets the 'first' serviceTime.
3. Customer B arrives second, waits at server 2. He gets the 'second' serviceTime.
4. Server 2 finishes before Server 1. Customer B gets served by Server 2 with the 'second' serviceTime.

However, Customer B should have been served with the 'first' serviceTime instead of the 'second', because he was served before Customer A despite arriving later.

**Comment by wmingchuan** [comment]
Call their service times only when they are being served. You can't check their service time in the Arrive or Wait class.

**Comment by JYeoZS** [comment]
For usage in serveEvent:

- consider looking at your server end time to decide if you are the next customer.
- consider calling getServiceTime to update the server end time.

**Comment by xj8423** [comment]
thanks all!
