### ISSUE TITLE
Ungraded Exercise #1 Level 5

### ISSUE THREAD

**Issue by granolaluvr69** [nus-cs2030/2223-s2#230]
Hi, just wanted to clarify something about level 5 for Ungraded Exercise 1. 
<img width="1733" alt="Screenshot 2023-02-23 at 8 12 40 AM" src="https://user-images.githubusercontent.com/120318851/220793242-625a8a8e-4699-459e-8118-2c1ab9365edd.png">

The structure of my code is as follows:
AckTransmitter :> ConnectedTransmitter :> Transmitter :> Host
ConnectedPager :> Pager :> Term

The relationships between my classes are modelled this way to avoid cyclic dependencies between them.

As seen for the above image, level 5 expects us to start tracking the number of connected pagers to each host and use the broadcast() method to make them beep.

For this issue, I am unsure of how to start tracking the connected pagers to each host. Would putting the ID of the terminals connected into an ImList and passing it down when I create new transmitters and pagers be a good idea?

In addition, they also want us to set the argument of the argument passed into the snd() method to make incomplete handshakes incompatible with it. 

Would that suggest that I should rethink the relationship of my transmitters as follows in order to prevent ConnectedTransmitters from being connected to new pagers?

AckTransmitter :> Transmitter :> Host
ConnectedTransmitter :> Host

**Comment by timothysashimi** [comment]
On the first part, can consider letting the subclasses of transmitters have a property ImList containing Terms that are connected to the transmitter and pass the list into the constructors of acktransmitter and connectedtransmitter.

As for the second part, ya i was thinking of not letting connectedtransmitter inherit from transmitter since snd can take in a transmitter or a acktransmitter

**Comment by e0968868** [comment]
You can consider adding an intermediate class between Transmitter and Host so that other types of Hosts can be taken in (same for between Pager and Terminal)

**Comment by granolaluvr69** [comment]
> On the first part, can consider letting the subclasses of transmitters have a property ImList containing Terms that are connected to the transmitter and pass the list into the constructors of acktransmitter and connectedtransmitter.
> 
> As for the second part, ya i was thinking of not letting connectedtransmitter inherit from transmitter since snd can take in a transmitter or a acktransmitter

> You can consider adding an intermediate class between Transmitter and Host so that other types of Hosts can be taken in (same for between Pager and Terminal)


Thanks for the help!
My current implementation is as follows:

Pager :> Term
ConnectedPager :> Term
AckTransmitter :> Transmitter :> Host
ConnectedTransmitter :> Host

I've implemented both your methods and it seems to have worked, but the issue now is that when I try to restrict snd()s arguments to be of type Transmitter, it doesn't allow for other hosts to connect, and if I try to relax it to accept Hosts, it does not prevent incomplete handshakes from connecting to the pager object. I suspect that this might be because all ConnectedTransmitters are Hosts, allowing incomplete handshakes to be passed through. Would it be advisable to make ConnectedTransmitter a standalone class to bypass this issue? Thanks again for the help.

**Comment by leroyteojy** [comment]
Hi, you can try to create an intermediate class between Host and Transmitter. Let Transmitter and AckTransmitter inherit from that intermediate class instead of Host directly, while your ConnectedTransmitter can still inherit from Host.

By doing so, you can restrict the snd method to only accept the intermediate class hence Hosts that have incomplete handshakes will not be able to access the snd() method.

**Comment by granolaluvr69** [comment]
Thanks for your sage advice, Leroy. Your wisdom helped me to pass all test cases for this exercise. You are really the most handsome man in all of SoC.
