### ISSUE TITLE
Practice Exercise 3

### ISSUE THREAD

**Issue by ugchongg** [nus-cs2030/2223-s2#240]
Hi! I have some queries on my understanding of the logic behind the implementation! May I ask

For Solid interface, do we need to specify the Volume() method because its extending from Shape3D interface which has volume specified as a method? In addition, can I check why SolidCuboid (which implements Solid) no longer requires the implementation of Volume to fulfil the requirement by Solid interface. 

Would it be because it's already extending from the Shape3D interface or because SolidCuboid extends from Cuboid which already have a public volume method (since it inherits from that it is taken that SolidCuboid has already fulfilled requirement of implementing a volume method)

**Comment by trwstin** [comment]
I think your question could be phrased and punctuated better, but I'll try to answer based on what I understand.

Solid is an interface just like Shape3D. Thus, it will simply inherit the method signature and does not require any implementation of Volume. And since interfaces cannot include implementation anyway, you cannot implement Volume in Solid instead of SolidCuboid to fulfill SolidCuboid's 'contract'.

Cuboid, which implements the Shape3D, has the Volume method because it needs to fulfill the 'contract' between itself and the Shape3D interface. Since SolidCuboid extends from Cuboid which has the Volume method, it only needs to implement the Mass method to fulfill the 'contract' between itself and Solid. So yes, your second point is correct in that regard.
