### ISSUE TITLE
[Lab 3] Test Case 7 Too Many Service Times Generated

### ISSUE THREAD

**Issue by cweisong** [nus-cs2030/2223-s2#252]
Lab 3 Test Case 7, too many service times generated as seen in the screenshot below
Anyone faced similar issue before? Any suggestions/advice on how to work a way around it?
Also, I am only calling` getServiceTime() `once in my Serve class.

Thank you in advance!

<img width="480" alt="Screenshot 2023-02-24 at 3 52 30 AM" src="https://user-images.githubusercontent.com/122463025/221105712-af34c51a-3a0d-46da-9e20-5bd5b0eeb571.png">

**Comment by orangejunhui** [comment]
i had the same problem - it's likely because there are other methods in inner classes like Server that may be using getServiceTime(). i don't know what your program structure is like, but one way to debug is to place a print statement inside the getServiceTime() in customer so you know how many times the method is being called and can look for these calls!

**Comment by Yew-Wei** [comment]
To add on to the previous comment, you could test out your code on Jshell using the customer arrival times in test case 7. I had the same issue and found the error in the implementation of my customer queue. Hope this helps :-)

**Comment by e0959170** [comment]
perhaps you could print out every instance that you call get service time to find out what's going on in your code

**Comment by cweisong** [comment]
Thanks all for your help, solved the issue!
