### ISSUE TITLE
Infinite loop once server qmax is greater than one

### ISSUE THREAD

**Issue by tali-a** [nus-cs2030/2223-s2#261]
Hi, I am generating wait  events repeatedly when the maximum queue length for one server is greater than one. If the server has a queue length of one the program behaves as expected. Checking through my implementation,(where an ImList of customers is stored as an attribute under Server), when the customer is not first in the list of customers (aka queue length greater than one), a new Wait Event is generated to be processed with an updated arrival timing for each customer. If I understand correctly, the source of the error may be that customers aren't being moved up to the first position in the list properly. I remove the first customer from the waiting customer list when I'm updating the server list in the Serve event class. the server list  is updated before the next event method is called.  is the infinite loop caused since the wait event never goes to serve and the customer list can never be updated to update the placement of customers? has anybody  faced something similar and do you have tips on how to resolve it ? many thankss

**Comment by haqanh** [comment]
Is it possible that you are not returning a new (updated) Server correctly? assuming you also have a list of server stored somewhere, due to the immutability you would need to return a new Server and then update your list of server with this new Server. I faced this issue when doing my Lab as well.

Hope this helps!

**Comment by e0959170** [comment]
hi i had this exact error and it plagued me for a few days </3

firstly like what the above commenter said you should try to make sure that you are updating the serverList with your updated server at all times

if you're already doing that, it may be because you're passing the server itself instead of the index of the server into your event objects  < this was the main source of error for my code.

hope this helps!

**Comment by jeffkhong11** [comment]
Try and see if you're getting the updated server from serverList in your serve event too

**Comment by jeffkhong11** [comment]
Try and see if you're getting the updated server from serverList in your serve event too

**Comment by taugwa** [comment]
yea for me this happened twice and once it was bc my serverlist didnt update properly (like what the others said). could check for this by adding a print statement to check ur queue? another time it was because my wait event was being called non stop cos I had no terminating condition to stop my programme frm calling the wait event

**Comment by rayray39** [comment]
> Hi, I am generating wait events repeatedly when the maximum queue length for one server is greater than one. If the server has a queue length of one the program behaves as expected. Checking through my implementation,(where an ImList of customers is stored as an attribute under Server), when the customer is not first in the list of customers (aka queue length greater than one), a new Wait Event is generated to be processed with an updated arrival timing for each customer. If I understand correctly, the source of the error may be that customers aren't being moved up to the first position in the list properly. I remove the first customer from the waiting customer list when I'm updating the server list in the Serve event class. the server list is updated before the next event method is called. is the infinite loop caused since the wait event never goes to serve and the customer list can never be updated to update the placement of customers? has anybody faced something similar and do you have tips on how to resolve it ? many thankss

Hi, just wanna ask if u have solved this issue, cos i am also experiencing the same issue and have been trying to debug for hours. i dont think i have not updated the servers, but somehow my last checkEvent keeps returning itself which i think could be because my doneEvent is not removing the customers correctly. But then again, my doneEvent works for qmax = 1, so i have no idea where its wrong. Any help would be appreciated! Thanks!

**Comment by tali-a** [comment]
Thanks everybody for the help <3 ! my errors were with updating the Server No and also because my WaitEvent was repeatedly generating itself . I wasn't updating my server list correctly because i was previously checking that the same customer wasn;t consecutively being added to the waitQueue, but what i should have been checking was whether a customer was already in the waiting Queue of a server list and then not adding the customer if that was the case. That helped me to resolve my error

>
