### ISSUE TITLE
Lab 4 level 5 implementing sort using comparable 

### ISSUE THREAD

**Issue by ugchongg** [nus-cs2030/2223-s2#266]
# Summary

Hi, 

I understand that there is a difference between comparable and comparator and that comparable which we have implemented in level 3 uses the compareTo method to help sort objects within the same class. I have searched up on how we can use it to help sort our ImList and they have used either Arrays.sort(_class_) or Collections.sort(_class_) _[class referring to the class that implements comparable]_. I have tried using Collections.sort(class) but it gives me this error. Any help would be appreciated, thank you!

## Description:

Also may I clarify the difference between Arrays, Collections and Iterable, I am quite confused .....

## Code Snippets

Attach code snippets (if any)

## Screenshots

![image](https://user-images.githubusercontent.com/121675791/221333660-91624cfa-46c8-4c96-acf5-737bfbccecc0.png)

**Comment by Ernestnzx** [comment]
You cannot to assign Collections to your `ImList`. Because `Collections.sort()` returns the type `void`

Im not too sure if you are allowed to use `Comparator` but you have to use the `ImList.sort()` function + create your own comparator class. If all else fails, you might have to come up with your own sorting algorithm + use the `compareTo()` method that you defined in your bookings...

Hope this helps!

**Comment by sjcze** [comment]
Collections.sort() returns void, sorting the array in place, instead of returning a new list. Because of this will not work on ImList.

**Comment by Jovan131** [comment]
You should use the ImList.sort() function and create your own comparator, and inside the implementation of the comparator class, you can consider using compareTo() to compare the values accordingly.

**Comment by ugchongg** [comment]
thank you all!
