### ISSUE TITLE
Issue with checkstyle: Multiple output detected.

### ISSUE THREAD

**Issue by Xequil1** [nus-cs2030/2223-s2#27]
# Summary
Codecrunch flagged my submission and wrote that there was multiple output detected, even though the checkstyle passed me on VIM.
Anyone knows what this means and how does one encounter such problems so that I can debug this.

![Screenshot (148)](https://user-images.githubusercontent.com/122268182/215102612-703c10c9-ac79-415a-9076-106e1250359d.png)

**Comment by lihongguang00** [comment]
Hi Xequil,

You can consider storing all your lines to be printed in a string that can be called in the `toString()` method, rather than printing them for each individual customer input. This would hopefully fulfil the last bullet point of the lab requirement. Hope this helps!

Lab requirement:
![image](https://user-images.githubusercontent.com/84987837/215106113-0f29c882-1eea-4456-903a-1b5754fd2350.png)

**Comment by JYeoZS** [comment]
Hi, 

I'm facing the same issue also, but there are no "System.out.println"s in all objects beside the main class.

Anyone face this same issue and how did you resolve it?

Thanks.

**Comment by lsy8117** [comment]
> Hi,
> 
> I'm facing the same issue also, but there are no "System.out.println"s in all objects beside the main class.
> 
> Anyone face this same issue and how did you resolve it?
> 
> Thanks.

same, i put all strings into one String variable and return that variable at the end, but still shows "multiple output detected" not sure why :((

**Comment by hwkchia** [comment]
Oops my bad... didn't realize that students would leave them there but commented. 😛

**Comment by JYeoZS** [comment]
Good Day Prof,

Yes, there were println in my comments for own reference. Guess changing the autograder resolved the issue. 

Thanks. :)

**Comment by danqiye1** [comment]
I guess this is resolved. Closing the issue.
