### ISSUE TITLE
Mismatched getServiceTime to Customer: Test Case 7

### ISSUE THREAD

**Issue by vanessakohh** [nus-cs2030/2223-s2#285]
I believe someone had asked a similar question two weeks ago but I was, unfortunately, unable to derive an answer from the comments.. I've implemented the getServiceTime function in the constructor of my Serve class. Perhaps it is not the wisest to do so in the constructor, however, I can't seem to think of alternative ways to define this value within the class. If anyone has encountered the same issue, I would very much appreciate some pointers. (lowkey begging though). Much thanks :P

<img width="371" alt="image" src="https://user-images.githubusercontent.com/122343675/221374159-03d3c071-88df-4e1e-9516-513f2403b637.png">

**Comment by aa01xx** [comment]
Hi, I have had this problem. The problem is not caused by how you defined your getservicetime in your Serve class. this problem is caused by:
You are allocating servicetime to customer based on their order of arrival/wait. I.E you created Serve once they arrive/wait.
But you should allocate servicetime to customer based on order of being served.
Only when they are actually being served, then only you should call getServiceTime().
You can consider checking that the server is actually free to serve before making new Serve. Hope this helps!

**Comment by JonathanCheeNUS** [comment]
Hi, agreeing with the earlier comment I believe you are obtaining the service time of each customer too early/ not in order resulting in the mismatch in service time assigned to each customer. For myself, my getServiceTime() was in the server class and called only when the serve event is polled and the server is free. Maybe a snippet of your implementation would help us understand where the problem is.

**Comment by Jeko1239** [comment]
I had a similar problem previously when i called getServiceTime() for customers while creating both Wait & Serve Event. I managed to solve it by making an extra event in between Wait and Serve, a Waiting Event. For my servers, I gave them a serverDoneTime every time they serve a new customer. So, if serverDoneTime > time of Event, I make the event reset. If server is supposed to be done with current Customer1 at 1200, but the next event called is Waiting(Customer2, 1150), then a new Event is created, Waiting(Customer2, 1200) where the time used is the server's done time. This way I only need to know the current customer's serviceTime, so I only needed to call getServiceTime() once. Hope it helps.

**Comment by tali-a** [comment]
Hi, i faced the same problem because i called get service time in my constructor. i removed it and replaced it with a default value , then called get  service time while i was updating my server list instead, which helped to resolve my error(though im not sure if thats the best option)

**Comment by vanessakohh** [comment]
> I had a similar problem previously when i called getServiceTime() for customers while creating both Wait & Serve Event. I managed to solve it by making an extra event in between Wait and Serve, a Waiting Event. For my servers, I gave them a serverDoneTime every time they serve a new customer. So, if serverDoneTime > time of Event, I make the event reset. If server is supposed to be done with current Customer1 at 1200, but the next event called is Waiting(Customer2, 1150), then a new Event is created, Waiting(Customer2, 1200) where the time used is the server's done time. This way I only need to know the current customer's serviceTime, so I only needed to call getServiceTime() once. Hope it helps.

Thanks! Life saver. Somehow this was the only method that worked with my implementation.
