### ISSUE TITLE
ex2 level3

### ISSUE THREAD

**Issue by veviana** [nus-cs2030/2223-s2#289]
my codes seems to only be checking for each cruise how many loaders is required and assigning the loaderId based on that. How do i check if the cruises have same arrival timing? if the cruises have same arrival timing, the numofloadersrequired would be the sum of loaders required for each cruise is that right?

![image](https://user-images.githubusercontent.com/94920324/221391291-89bf247f-67f9-4db4-a152-34e94f2e834d.png)

**Comment by sp4ce-cowboy** [comment]
I had a similar issue which i managed to fix by having a **currentCounter** inside the for loop that iterates through the cruises ImList, to keep track of how many loaders have been assigned to the current cruise, and a **totalCounter** outside the for loop to keep track of how many loaders have been created in total.

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/19762596/221391522-336c8b97-4bd8-4bee-9c67-024ad73bf081.png">

So for the first few cruises, the code will skip past the expired services list because there would be no currently active services. When it gets to the part where a new loader is to be created (_...create new ones and deploy them.._) the loaderId used to create this loader would be the totalCounter outside the loop (`currentCounter++, totalCounter++`) . When another cruise arrives and an expired service's loader is used, you can simply get the loaderId of that loader and assign that to the new service (`currentCounter++`). When implemented this way, it wouldn't matter if the cruises arrive at the same timing, as the loop that iterates through the cruises would do so sequentially.

**Comment by veviana** [comment]
> I had a similar issue which i managed to fix by having a **currentCounter** inside the for loop that iterates through the cruises ImList, to keep track of how many loaders have been assigned to the current cruise, and a **totalCounter** outside the for loop to keep track of how many loaders have been created in total.
> 
> <img alt="image" width="1296" src="https://user-images.githubusercontent.com/19762596/221391522-336c8b97-4bd8-4bee-9c67-024ad73bf081.png">
> 
> So for the first few cruises, the code will skip past the expired services list because there would be no currently active services. When it gets to the part where a new loader is to be created (_...create new ones and deploy them.._) the loaderId used to create this loader would be the totalCounter outside the loop (`currentCounter++, totalCounter++`) . When another cruise arrives and an expired service's loader is used, you can simply get the loaderId of that loader and assign that to the new service (`currentCounter++`). When implemented this way, it wouldn't matter if the cruises arrive at the same timing, as the loop that iterates through the cruises would do so sequentially.

if there is expiredService, we have to make it active, so do we retrieve the loaderID from the expiredService and create a new Service using this loaderId? sorry! a little confused with currentCounter, is currentCounter the loaderId?

**Comment by sp4ce-cowboy** [comment]
Yes exactly. You would additionally need a getter method within the Loader class that returns the loaderId.

The currentCounter is used to keep track of how many loaders have been reassigned/created for the current cruise, so you can compare with numOfRequiredLoaders for that current cruise and decided if you have enough or need more loaders for that current cruise. The currentCounter resets back to 0 for every cruise.

For example:

`int totalCounter == 1 \\ so you can start at LoaderID from 1`

`<< start of cruise loop >>`
   
 ` ... `
    ` int currentCounter = 0 `
    ` int requiredLoaders = ? `
    `... // some logic involving those two `

`<< end of cruise loop >>`

**Comment by veviana** [comment]
> Yes exactly. You would additionally need a getter method within the Loader class that returns the loaderId.
> 
> The currentCounter is used to keep track of how many loaders have been reassigned/created for the current cruise, so you can compare with numOfRequiredLoaders for that current cruise and decided if you have enough or need more loaders for that current cruise. The currentCounter resets back to 0 for every cruise.
> 
> For example:
> 
> `int totalCounter == 1 \\ so you can start at LoaderID from 1`
> 
> `<< start of cruise loop >>`
> 
> `...` `int currentCounter = 0` `int requiredLoaders = ?` `... // some logic involving those two `
> 
> `<< end of cruise loop >>`
> 
> If implemented properly, the only loaderId needed when making new loaders would be the totalCounter outside the loop. So every time a loader is reused from expiredService, there is no need to assign a new loaderId as the loader inside the expiredService would already have had its loaderId assigned when it was created (which would have been the totalCounter at the point of its creation.)

thankyou so much!
