### ISSUE TITLE
Too many service times generated.

### ISSUE THREAD

**Issue by jayson237** [nus-cs2030/2223-s2#293]
Does anybody know what codecrunch mean by this?

![image](https://user-images.githubusercontent.com/110618399/221398752-02b2b029-eb04-4c91-aab2-1105ca14c506.png)

![image](https://user-images.githubusercontent.com/110618399/221398834-6f6833c2-be9b-4f5f-9e2f-63fc05ec4588.png)

**Comment by whsiah** [comment]
This means that your code is calling the getServiceTime() method more times than "allowed". The method should only be called once per customer that is served. As several other classmates have pointed out, the best way around this problem is to call the method only when a customer is about to be served.

**Comment by JYeoZS** [comment]
Sounds like same problem as few others like:
https://github.com/nus-cs2030/2223-s2/issues/228

=> After your customer is served, how did you update the server? You should update only in one event. Which would be best event to do the update?

=> Problem could be conceptual also. Are you calling servicetimes many times in wait event class because you're trying to determine if you are next customer?
=> Consider using the server to determine if you are next customer to be served.
=> Then you as the customer with many people ahead, perhaps find a way to loop the event again and again until it's your turn to be served.

**Comment by wmingchuan** [comment]
Make sure you only call getServiceTime when necessary, it should be equal to the number of customers served

**Comment by trwstin** [comment]
You can add a line of System.out.println() within your getServiceTime() method, to track how many times you are calling it. This could help you identify the scenarios in which you are calling the method more times than necessary.

**Comment by cweisong** [comment]
I faced this issue as well. To add on to the previous comments, you may try resolving using these methods,

(1) Use getServiceTime() once & only in your Serve class.

(2) If you happen to have a if-else condition or if you need to call it multiple times in your Serve class, you can try assigning getServiceTime to a variable and use the variable as required.

Hope this helps!

**Comment by aowz** [comment]
You should only be calling getServiceTime when necessary. For me, it's only invoked when a serve event is created. This ensures that those customers that aren't served don't call service time unnecessarily.

**Comment by Suraj2P** [comment]
I had this problem too although I was calling it only once. I realized if you are already only calling it once it is likely that your queue is not being updated and is not serving the right customer at the right time. You can try this test case to check.

2 3
0.500
1.100
1.200
1.300
1.400
1.500
1.600
1.700
1.800
1.900
10.00
11.00
12.00

The last line of the output should be [0.900 12 1]

**Comment by Suraj2P** [comment]
I had this problem too although I was calling it only once. I realized if you are already only calling it once it is likely that your queue is not being updated and is not serving the right customer at the right time. You can try this test case to check.

2 3
0.500
1.100
1.200
1.300
1.400
1.500
1.600
1.700
1.800
1.900
10.00
11.00
12.00

The last line of the output should be [0.900 12 1]

**Comment by Yew-Wei** [comment]
Had this issue and used the method stated in the comments above to debug. I faced this issue previously as well and I realised the error was in the updating of my queue. (even though my code passed the test cases in the examples shown on the lab3 exercise itself)

**Comment by EvanCh08** [comment]
This happens because you are calling getServiceTime() when you are not supposed to, for example you call it in your leave. Try calling getServiceTime() only when serve. Hope this helps.
