### ISSUE TITLE
Test Case 7 Wait Class

### ISSUE THREAD

**Issue by shir-err** [nus-cs2030/2223-s2#294]
I saw that there were similar posts on this issue and realized that I have been assigning a customer's serving time in wait class but I'm not too sure how to go about fixing it...
I tried to check in the Done class whether the server still had customers in queue and to return a Serve event after but there was cyclic dependency... I'm also not too sure how to make it such that a customer continues to wait as returning the event itself results in a never-ending loop? Any advice on how to make a customer continue waiting in the Wait class? or any tips to work around this error? thank you!!

**Comment by 0liverkong** [comment]
Do you have both of these? 
1. Servers with a nextFreeTime attribute
2. invisible wait events / a hidden MoveQueue event that signifies a Customer moves up the queue but is not served yet

**Comment by trwstin** [comment]
> I'm also not too sure how to make it such that a customer continues to wait as returning the event itself results in a never-ending loop?

This method does not exactly involve the Wait even returning 'itself', since you will be returning a new Wait event with certain updated details - hence there will not be a never-ending loop. 

First, make sure that your conditions for deciding between serving/continue waiting are correct.

Second, note that if a customer continues waiting, you should still update their arrivalTime to match their respective Server's latest finishTime.
