### ISSUE TITLE
Ex 2 how to remove correct loader from active queue

### ISSUE THREAD

**Issue by ghost1nthemachine** [nus-cs2030/2223-s2#298]
what i did was to make a copy of active queue and then remove from this copy queue to prevent the iteration from messing up. 

activeCopy = activeCopy.remove(0)

however it becomes an issue when i dont want to remove the first loader of the queue cause they are still in service. hw shld i fix this?

![image](https://user-images.githubusercontent.com/125187978/221405147-1ee95b74-aa67-4ed2-a90d-5953c5ddc4b6.png)

**Comment by granolaluvr69** [comment]
firstly, you should not always be removing the first element from your queue of active services, because you are not accounting for the case where it might not be expired. 

you might want to try adopting an approach where you iterate through the **indices** corresponding to the services which are still active instead. 

secondly, adopting this approach, when you remove an element from the list, take note that the size of your list also decreases by one, this necessitates a decrease in index by one to compensate for the removal of this element.

hope this helps!

**Comment by ghost1nthemachine** [comment]
> firstly, you should not always be removing the first element from your queue of active services, because you are not accounting for the case where it might not be expired.
> 
> you might want to try adopting an approach where you iterate through the **indices** corresponding to the services which are still active instead.
> 
> secondly, adopting this approach, when you remove an element from the list, take note that the size of your list also decreases by one, this necessitates a decrease in index by one to compensate for the removal of this element.
> 
> hope this helps!

Thank you! :)
