### ISSUE TITLE
Ungraded Ex 1: What does CompletedHost do?

### ISSUE THREAD

**Issue by taugwa** [nus-cs2030/2223-s2#307]
hi, am currently watching the video walkthrough for ungraded ex 1 and the TA mentioned that to prevent incomplete handshakes from being passed to .snd, we can create a CompletedHost class that calls the constructor of Host. then, we can have Transmitter extend CompletedHost to ensure that .snd only takes in compatible types (timestamp 9:53 - 11:30).

i don't really understand how this works, can anyone explain the logic behind this? thank you!

**Comment by weitatftw** [comment]
as the question mentioned that snd should only take in either a new transmitter or a transmitter that has completed one full handshake, there is a need for us to create a new host class that signifies either a new transmitter or a transmitter that has completed its handshake. this is so that we can use the CompletedHost as an input to snd and this prevents snd from accepting hosts that have not completed a handshake.

**Comment by taugwa** [comment]
oh damn thank you 🧠

**Comment by nigel-tannn** [comment]
A CompletedHost signifies that a Host is ready to receive another handshake.  This prevents another Terminal from "hijacking" the handshake midway through.
