### ISSUE TITLE
anyone knows what is causing this error? 

### ISSUE THREAD

**Issue by eunicel23** [nus-cs2030/2223-s2#318]
<img width="1403" alt="Screenshot 2023-03-05 at 10 15 28 PM" src="https://user-images.githubusercontent.com/122519056/222969514-835a3978-01eb-4963-8362-f6c40a1ca76e.png">

**Comment by NeoHW** [comment]
you could try checking if a cancelled task could still be edited as it seems that it did not happen in this test case

**Comment by Blackknight25** [comment]
you can try editing a task such that the list needs to be reordered chronologically, then try to cancel the task. In my case the wrong task was cancelled because i didnt reorder the list in chronological order in the edit method but only did that towards the end, so you could probably sort the list within the edit method as well:)

**Comment by leonardwx** [comment]
perhaps can check the loop of the cancel method? make sure the cancelTask is only created upon the calling of particular index

**Comment by eunicel23** [comment]
> 

yep i that was exactly my problem thanks!! :)
