### ISSUE TITLE
Missing a Task

### ISSUE THREAD

**Issue by weitatftw** [nus-cs2030/2223-s2#319]
# Summary
Put a summary of the problem here
I'm currently facing this issue where my view method does not include one of the tasks in the list of tasks in the planner. Does anyone have any idea what is causing this issue? This is the only test case that I don't pass

## Screenshots (if any): 
<img width="546" alt="Screenshot 2023-03-06 at 12 41 10 AM" src="https://user-images.githubusercontent.com/79369027/222973802-5eab5a6a-2cc8-45aa-a96a-39be01da41b1.png">

**Comment by e0959170** [comment]
maybe can check your comparator? you may have accidentally filtered out the event that you need to display

**Comment by shionhigashi** [comment]
i think you can check if your list takes in the list of tasks that is within the recurring task, not just taking in the recurring task itself

**Comment by trickypepe** [comment]
you can try checking if your filter omitted out the entire recurring task

**Comment by dylanlo8** [comment]
1) I dont think its an issue with your comparator since all other test cases had passed. 
2) Maybe there is an issue with your filtering in your RecurringTask class
2) If all else fails, maybe you can consider a general implementation of an extract method where you return a ImList<Whatever general task>() in all variations of tasks so that all types of tasks follow this consistent format. Of course cancelledtasks and cancelledrecurring tasks would return an empty list. Then within your view method you can just make use of whatever list has been returned from each task and add on to the "output" list

**Comment by leonardwx** [comment]
you can check whether did you filter/remove the cancelled tasks inside the RecurringTask,

**Comment by 0liverkong** [comment]
make sure you extract out the tasks from the recurring task correctly - you may have overlooked that

**Comment by ryantangmj** [comment]
It might be because you did not extract your tasks from recurringtask

**Comment by Aron113** [comment]
you might need to check if you extracted the task correctly or incorrectly filtered

**Comment by leonlu178** [comment]
you can check whether you have extracted that specific task from the list of tasks in RecurringTask

**Comment by weitatftw** [comment]
Thank you everyone for the help! I found that I only added the task component of the recurring task and I forgot to iterate through the list of tasks within the recurring task itself, hence the missing task
