### ISSUE TITLE
What does p in planner p represent? A list?

### ISSUE THREAD

**Issue by jayson237** [nus-cs2030/2223-s2#325]
Quite confused on what to do for level 4

**Comment by nicholasteow** [comment]
Hi are you referring to this line here?
### Planner p = new Planner() 

If yes, the planner is just a class with no constructors.  If you wish to make it hold lists, it will work too. Depends on how you implement it

**Comment by jaejayrome** [comment]
To circumvent this, you could implement constructer overloading but ensure that the ImList Property within the the Planner class is being initialised within the empty() constructor.
Hope this helps!

**Comment by leonardwx** [comment]
Level 4 Planner p = new Planner() should return a empty statement since the ImList is empty. If there are tasks inside the ImList, the toString() method should be able to print out the list of tasks (Task, Cancelled Task, RecurringTask, Cancelled RecurringTask)

**Comment by Nicknzk** [comment]
overloading would be good for instantiating planner. so u can initially have the empty planner and then add things and return a new planner with the "things added"

**Comment by littlemidget3** [comment]
Agreed with Nicknzk. 2 constructors, one being empty could perhaps be a good way to approach this. As new Task/RecurringTask/CancelledTasks are added to the planner, we should be returning a new Planner in the spirit of effect-free programming. In order to keep track of past added tasks, a second constructor that takes in an ImList of tasks would be good. The next question is, what is the type accepted in the ImList for the Task/RecurringTask/CancelledTasks to be added.
