### ISSUE TITLE
Last test case (DayView)

### ISSUE THREAD

**Issue by nurin534** [nus-cs2030/2223-s2#348]
Hi! My CanceledTask has a method to return an empty list but somehow I still failed the last test case. Any advice?

![image](https://user-images.githubusercontent.com/123313531/224213975-9fc88c47-0080-476a-b467-07c9c77d3bdc.png)

**Comment by shir-err** [comment]
maybe you check if your recurring task method checks whether the sub/recurring task was cancelled or not? it seems like your recurring task adds the task immediately once the day matches and does not call the method that returns an empty list if it is a cancelled class/ returns a list of task if it is a normal task

**Comment by hhuilingg** [comment]
i think u need to make sure that the method for return the list in ur RecurringTask, should be a list that is after edit and cancel (so preferably u will need a ImList property in your RecurringTask, then return that to use it in DayView)

in ur DayView you should extract all the tasks in the list using addAll (so that it became one task and not for eg. Recurring task will become a list instead) then u can execute the method (which is the one u mentioned for cancelledTask).

hope it helps! :)

**Comment by weitatftw** [comment]
i believe that this is the same issue as #339, you can check it out for a possible solution
