### ISSUE TITLE
Lab 5 Test case 9_03

### ISSUE THREAD

**Issue by timothysashimi** [nus-cs2030/2223-s2#357]
Hi, can i ask why my code is facing this issue on code crunch where theres time limit exceeded?

![issue](https://user-images.githubusercontent.com/120008429/224468503-19991d01-8428-4b5a-bb6e-bfa75ac5eb11.jpg)

**Comment by alvintjw** [comment]
Sorry isn't test case 9_03 a different input than the one you shown in the terminal

**Comment by timothysashimi** [comment]
> Sorry isn't test case 9_03 a different input than the one you shown in the terminal

eh ya oops okay but can I ask why its failing the private test cases

**Comment by littlemidget3** [comment]
usually if there is a time limit exceed, it means that you may be in a infinite loop. Try putting a println statement in where you suspect the loop may be to find the source of your bug.

**Comment by Nicknzk** [comment]
Thread #363 also brought up a similar issue

in general i feel that Time Limit exceeded doesnt mean that ur code is too long but rather it continues forever.

In this case, id imagine it has something to do with the start time since the first event is "0.000 1 arrives"

Maybe u can try to look at ur logic in the ArriveEvent, it may be something like ">" vs ">="
