### ISSUE TITLE
Code works but codecrunch showing different output

### ISSUE THREAD

**Issue by limrik** [nus-cs2030/2223-s2#36]
<img width="264" alt="Screenshot 2023-01-29 at 1 42 05 PM" src="https://user-images.githubusercontent.com/64995992/215307416-a264b4f6-f594-49ad-bb83-6f6e60a1be32.png">

My code seems to run correctly in the terminal

![telegram-cloud-photo-size-5-6246754938617183352-y](https://user-images.githubusercontent.com/64995992/215307433-533dcef9-c61c-4ab4-8d89-29dab4058fb5.jpg)

but this is what it shows on codecrunch.

Not sure why this is happening... have already tried to recompile my code and reupload to codecrunch but it still shows the same thing

**Comment by lihongguang00** [comment]
Hi limrik,

May I ask what are your local test case values, and how did you derive them from codecrunch's private test case values? 

Additionally, you can consider how your code behaves if a subsequent customer arrives at the same time the previous customer leaves (i.e. customer 1 leaves at 1.500, customer 2 arrives at 1.500).

**Comment by limrik** [comment]
<img width="82" alt="Screenshot 2023-01-29 at 2 21 55 PM" src="https://user-images.githubusercontent.com/64995992/215308888-af646a8a-ff9f-4f4c-9afb-8b49e991d52e.png">

Hey lihongguang, 

that was what I did, here is my test case for 6.in

**Comment by lihongguang00** [comment]
Hi limrik, 

Notice that your test case assumes that your shop only has 1 server. However, from the private test cases on codecrunch, since your customers can be served up to 7 servers, it implies that there are at least 7 waiters for this private test case. Try the following test case instead and see how your code behaves.

7
0.500 1.000
1.500 1.100
2.600 1.200
3.800 1.300
5.100 1.400
6.500 1.500
8.000 1.600

If your code is behaving correctly, your output should match the one expected by codecrunch. Hope this helps, cheers!

**Comment by limrik** [comment]
Ahh great that explains why! Thanks!
