### ISSUE TITLE
Test Case 9_12 [Incorrect but no output]

### ISSUE THREAD

**Issue by zxciisdbniel** [nus-cs2030/2223-s2#372]
# Summary

Any idea what could be causing this issue? This is a long test case (512++ lines but code crunch doesn't show the entirety of it), and shows an incorrect output rather than time limit error, but it doesn't show any output so I'm not sure where I went wrong.

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

![image](https://user-images.githubusercontent.com/96293687/224529847-22f40359-e7b5-48eb-af61-21c6e7b80a1e.png)

**Comment by e0959170** [comment]
time limit probably means u have a never ending for loop somewhere in your code!

**Comment by xyxyiuxy** [comment]
this should be due to an infinite loop created. I have encounter this before, and the loop is created when I go from WaitEvent to my WaitAgainEvent. You may check the condition for customer to enter a WaitEvent/WaitAgainEvent,  and check the time is updated correctly in server list every time. you can print out some statements to see where exactly you created this loop. Goodluck!
