### ISSUE TITLE
[Lab 5.1] Test Case 9_03

### ISSUE THREAD

**Issue by cweisong** [nus-cs2030/2223-s2#379]
Lab 5.1 Test Case 9_03, wrong output for Customer 11 as seen in the first screenshot below.
Anyone faced similar issue before? Any suggestions/advice on how to work a way around it?
I am only calling getresttime()once in my Done event. 
I did not implement a Rest event.

Also, I would like to check if I am calling getresttime() too many times.
Currently I am calling it once every Done event as seen in the second screenshot below.
Would like to know if that is incorrect.

Would appreciate any advice! Thank you.

<img width="445" alt="Screenshot 2023-03-12 at 10 17 09 PM" src="https://user-images.githubusercontent.com/122463025/224550534-69bda963-7ec3-4de8-905a-344241974fdd.png">

<img width="192" alt="Screenshot 2023-03-12 at 10 21 17 PM" src="https://user-images.githubusercontent.com/122463025/224550744-641bae1e-ef11-405b-867a-efe0f3616d06.png">

**Comment by sethteo** [comment]
hi! what is your sequence of events right now

**Comment by sethteo** [comment]
I think by only using a DoneEvent to determine the resttimes might cause an error such as
0.100 1 arrives
0.100 1 serves by 1
0.200 2 arrives
0.200 2 waits at 1
1.100 1 done serving by 1
1.100 2 serves by 1 (but your server might be resting)
which is seen in lines 45-46

I think you can instead implement a RestEvent which transitions from your DoneEvent (not sure of your implementation but you can input the getRestTime() + your DoneEvent's current time as an argument for your RestEvent's constructor)

Based on your output you are not calling getRestTime() too many times as you had 6 "calling restTime" and 6 done events, plus CC didnt flag it out for your test cases.

**Comment by taugwa** [comment]
Hi i had the exact same issue! Heres the thread: https://github.com/nus-cs2030/2223-s2/issues/365
For me it was a problem with the serve event during my buffer wait event not having the latest endservicetime of the server--since i generated it before the endservicetime is updated with the rest time of the server

i did it without a rest event but I think whether or not you have a rest event doesnt rly matter for 5.1

**Comment by tallkoh** [comment]
didn't have rest event either - i think this might be a problem in your conditions for canwait() (or methods to that effect) or your stub event (that is between wait and serve). essentially just make sure your server's timing is always updated and that you're checking it!

**Comment by trickypepe** [comment]
Think the telltale sign that 1 immediately proceeds to serve 11 the moment he's done with 10 (at 15.013) when he's supposed to take a rest (16 arrives and waits at 1 instead of being served directly in the expected output) means that you are checking the availability of server at the wrong place (maybe you are popping the server's queue right after a served event). 

I ran into a similar issue and solved it by reordering some checks.

**Comment by kayeugenia** [comment]
i did not have rest event too! i think it is possible to implement this code and you're definitely on the right track. just make sure that you return the correct event (Serve/ another Wait or PendingWait) within your Wait Event. For me, my issue was that my conditional flows only check if the customer is in the first queue, and if it is,  i return a new Serve event. However, given that now the server can rest too, we should add another condition which is that the timestamp >= server.nextAvailable()

**Comment by yinshuennn** [comment]
maybe you want to check on your conditional statement in your intermediate WaitEvent to see if you're correctly checking the time in which the customer can be served, like what @kayeugenia mentioned above! my mistake was that my inequality was actually flipped so it was checking for the server's nextAvailTime against the timestamp of my Buffer event incorrectly, hope this helps!

**Comment by 12thfret** [comment]
Hi, i too encountered this problem. My issue was not considering the customer queue length. In my previous implementation, if qMax was 2, i would check for availablility in the queue by using queue.size() <= qMax. There is an equality sign since if the first customer in the queue is being served, the queue can still accomodate 2 other people. Now however, given the case that the first customer in the queue might not necessarily be served (if the server is resting), i had to change my conditional statements when checking for availability. Not sure if i completely sidetracked but hope this helps abit.

**Comment by cweisong** [comment]
Solved it,
Thanks a bunch friends!
