### ISSUE TITLE
Question about interface in the Maybe Context

### ISSUE THREAD

**Issue by yugan01** [nus-cs2030/2223-s2#384]
## Topic:

Maybe Interface/Optional interface

## Screenshots

![image](https://user-images.githubusercontent.com/122327042/224587792-871a4f06-fec8-47e5-93a3-7012b2fb8ac9.png)
# Description

Hi! I have 2 questions, firstly, I understand interfaces are abstract and cannot be instantiated, so I am confused as to why the static method above has new Foo<T>().
In the screenshot below, I used jshell to write new Foo<T>() and it does not work as expected so I am unsure as to why new Foo<T>() returns an instance of the Foo interface.

![image](https://user-images.githubusercontent.com/122327042/224587820-151c107a-2dd0-45af-b79a-4f560058247d.png)

Secondly, this static method is used so that objects of the foo interface are unable to stop the pipeline by calling of(). However, I understand that static methods are in all of the instances of the class so I am unsure as to why the instance is unable to call the of method.

Thank you in advance!

**Comment by ongjunfeng17** [comment]
From the way I see it and as you have aptly pointed out, we cannot instantiate an interface (since it defies the object oriented model). Calling new Foo<Integer>() would be trying to instantiate an interface. After doing some googling, the reason why the static method can return new Foo(), is because we are not creating an instance of the interface. Instead, we are **defining an anonymous class that implements the interface**, and instantiating that class.

**Comment by ongjunfeng17** [comment]
As for the 2nd question, I think the reason why it throws the error is because "of" is not a method defined in the inner class implementation of Foo(?). So we are allowed to call methods such as filter if we defined it as an inner class method (just like in the picture) but not of. I am not too certain about this.

![photo_2023-03-13 17 28 22](https://user-images.githubusercontent.com/120620166/224660990-2068e6b8-c8b5-4b04-8cdb-a904f27a335a.jpeg)

**Comment by yugan01** [comment]
Thank you!
