### ISSUE TITLE
compilation error with test case 7

### ISSUE THREAD

**Issue by wyqng1234** [nus-cs2030/2223-s2#394]
# Summary

my submission generated a compilation error when testing test case 7. I'm also not sure what the problem with my code is that generated an output like this. can anyone point me in the right direction :"

## Screenshots
![Screenshot 2023-03-14 at 5 10 26 PM](https://user-images.githubusercontent.com/124020122/224952795-7ac136c4-fcd1-4282-abde-985d3b9e4601.png)

Screenshots (if any)

**Comment by yoyo1605** [comment]
hi, I have the exact same issue! do let me know if you managed to solve it.

**Comment by bdonong** [comment]
Hi, I also encountered the same problem last time, but I resolved it by only calling `.getServiceTime()` in the Serve Event. Calling it in say, the arrive event, messes up the order of the server times, causing the service times to be swapped. 

You can refer to #103 for more help :)

**Comment by easypzlemonsqueezy** [comment]
hi! you might have called getservicetime() more than you should have and that resulted in a discrepancy in the servicetimes for the customers

**Comment by joshlimwe** [comment]
hi I also encountered a similar problem, there shouldnt be a problem with your event comparator and event pq if this issue is similar to mine, your getServiceTime() seems to be called correctly for customer 5, but the issue may be that the timing that is passed into your done event when your serve event is finished may be wrong or not updated, and your issue may also be related to when there is multiple customers in your queue as thats why your timing for customer 9 and 10 are correct. Hopefully this helps:)

**Comment by codecode24** [comment]
Your program is treating the servicetime for customer 7, which is 0.415 (calculated from the expected output), as the servicetime for customer 4. Maybe check your implementation of getservicetime()?

**Comment by niclee1219** [comment]
hi! perhaps this might help, was stuck with a time discrepancy as well!

https://github.com/nus-cs2030/2223-s2/issues/418
