### ISSUE TITLE
Lab 5.2 Test Case 9_9

### ISSUE THREAD

**Issue by wongjingwen** [nus-cs2030/2223-s2#399]
![Screenshot 2023-03-14 204922](https://user-images.githubusercontent.com/120257984/225005898-9fa3866e-4224-4da3-af16-8e92ea8e9394.jpg)

Hi, Im not sure why my output is not printing a leave event. Could it be how i assigned my Servermanager?

**Comment by 0liverkong** [comment]
does you function that assigns customers to queues look at the queues and only the queues?

**Comment by wongjingwen** [comment]
Does every self-check counter have a queue? This means that i need to update all the self-check counter queue if there is a customer added/removed from the queue?

**Comment by 0liverkong** [comment]
> Does every self-check counter have a queue? This means that i need to update all the self-check counter queue if there is a customer added/removed from the queue?

depends on your implementation. i only have one queue for self check

**Comment by 0liverkong** [comment]
> My implementation is a single queue stored on another class . However, i have trouble extracting specific servers for that particular Event to store the server. Is there a way to ensure that it outputs the correct server

do you have helper methods like getFreeServer(double time)?

**Comment by wongjingwen** [comment]
Nope. Im not sure how to use the static methods

**Comment by 0liverkong** [comment]
> Nope. Im not sure how to use the static methods. Can we use a static method of a subclass although its compile time type is that of its parent class?

im not sure if that's possible but i never had to care about inheriting static methods. one of the most useful methods i think you can make is below. returns -1 if the servers in the ImList are all busy, the ? extends Server is to allow for ImList<SelfCheckout> to be inserted as an argument as well since selfcheckout extends from server for me.
<img width="605" alt="Screenshot 2023-03-15 at 1 48 56 AM" src="https://user-images.githubusercontent.com/122248867/225093700-bd4a4eb2-320a-4e5b-8870-952e0919fb43.png">

**Comment by wongjingwen** [comment]
Ok. I will go and try it out . Thanks for the help.

**Comment by wongjingwen** [comment]
Thanks for the help, I have managed to resolve the issue. The problem was not updating the queue.
