### ISSUE TITLE
how to not print out 'unwanted' serve event?

### ISSUE THREAD

**Issue by hcyrr** [nus-cs2030/2223-s2#403]
# Summary

referring to codecrunch's 3.in's test case, my output is the same as their output, except that i have this serve event (5.053 6 serves by 1) which i do not want to be printed as this event just helps me to generate the correct serve event for 6, which is at 5.902 (as seen below). how should i prevent this event from being printed? initially i wanted to check whether server is currently resting by putting some logic in Serve's toString method, but i realised i cant do that since i would need servers as an input in toString for me to get the updated status on whether my Server is resting, and i dont think there shld be any input for toString() right..? also ignore the rest events shown haha its for my own debugging. please point me in the right direction thank youu

## Screenshots

Screenshots (if any)
![B3A56948-A57D-4AA7-8C54-CDCB487081D9_4_5005_c](https://user-images.githubusercontent.com/126330380/225320980-b15f01e1-768a-4f35-be77-dfb6a9e4d54b.jpeg)

**Comment by trwstin** [comment]
So if I'm understanding this correctly you are generating Serve events within your Serve event in order to get the correct time?

You can add a boolean to the constructor (i.e. toPrint), and use that in your Serve event's toString to decide if it should be printed or not. This is something I did for my Wait event which generates Wait events until a customer is ready to be served.

For example:
Let's pretend the constructor only takes in a double for timing and the boolean I mentioned above.
(5.053, false) -> print ""
(5.902, true) -> print "5.902 Server..."

**Comment by hcyrr** [comment]
> So if I'm understanding this correctly you are generating Serve events within your Serve event in order to get the correct time?
> 
> You can add a boolean to the constructor (i.e. toPrint), and use that in your Serve event's toString to decide if it should be printed or not. This is something I did for my Wait event which generates Wait events until a customer is ready to be served.
> 
> For example: Let's pretend the constructor only takes in a double for timing and the boolean I mentioned above. (5.053, false) -> print "" (5.902, true) -> print "5.902 Server..."

i did this for my Wait event as well! but i dont think i can do this here bc (5.053 6 serves by 1) is generated earlier on, and at that point in time we wldnt know if the server needs to rest so i wldnt be able to determine whether to put true or false in the constructor

**Comment by trwstin** [comment]
> i did this for my Wait event as well! but i dont think i can do this here bc (5.053 6 serves by 1) is generated earlier on, and at that point in time we wldnt know if the server needs to rest so i wldnt be able to determine whether to put true or false in the constructor

ohhh ok i think i'm starting to understand... so the way you're accounting for restTime is by creating a new Serve event from the current Serve Event, with the restTime added to it? Meaning as soon as you execute serve, you already retrieved the restTime?

**Comment by trwstin** [comment]
If you are, then you might not get the correct results, since you risk invoking the restTime supplier in the wrong order. For example:

0.000 Cust A served by Server 1
0.100 Cust B served by Server 2

At this point in time, the serviceTime supplier will be invoked. Based on my understanding of your implementation, you are invoking the restTime supplier at this point in time as well to generate your additional Serve event.

Meaning that in this case, Server 1 would get their restTime before Server 2.

Now, what if Server 2 finishes earlier than Server 1?

0.200 Cust B done served by Server 2
0.400 Cust A done served by Server 1

Since Server 2 finished first, he should rest first before Server 1. Hence, his restTime should be based on the **first .get()** of the supplier. However, since you assigned rest time during serve, he is resting based on the **second .get()**. This will lead to problems with your timing later.
