### ISSUE TITLE
Lab 5.2 Test Case 9_11

### ISSUE THREAD

**Issue by wongjingwen** [nus-cs2030/2223-s2#405]
# Summary

Im not sure what is wrong with the output. I have a condition to check if any of the self checkout server is available. However, it does not return me a wait event although my checkout servers are all occupied.

## Screenshots
![Screenshot 2023-03-15 223925](https://user-images.githubusercontent.com/120257984/225344215-63871f39-358c-4223-bd02-9d2ba0b23d40.jpg)

Screenshots (if any)

**Comment by sethteo** [comment]
hi! you can try referring to [https://github.com/nus-cs2030/2223-s2/issues/398](#398) or [https://github.com/nus-cs2030/2223-s2/issues/368](368) they all face similar issues. Most probably is that you are not looping through all selfcheckouts to get the shortest available time as well as if the selfcheckout is free to serve

**Comment by wongjingwen** [comment]
How do you ensure the selfcheckout is free to serve? Keeping track of a queue is only when there are customers queuing up.

**Comment by trwstin** [comment]
can you send the full screenshot? I suspect that in your output customer 13 is being served by whoever he waited at.

hence, instead of being served by self-check 4, he is still waiting for, say, self-check 3 to finish. this causes 4 to be free and serve 15 immediately upon their arrival.

if this is the case, then your issue lies with a customer not properly switching to the fastest available self-checkout

**Comment by wongjingwen** [comment]
Thanks for the help. The error lies with my customer not properly switching to the fastest available self-checkout.
