### ISSUE TITLE
Exercise 4: or() and flatMap() method

### ISSUE THREAD

**Issue by emmannyyy** [nus-cs2030/2223-s2#424]
Hi! 

I don't really know what is the correct strategy to solve the Or method, here. 

**1. The or() method**
My current method implentation is as follows:
public Maybe<T> or(Supplier<? extends Maybe<? extends T>> supplier) {
    if ( this.isEmpty()) { 
        return supplier.get();
    } else {
        return this;
    }
}

having an issue because my supplier.get() throws a capture issue:
![image](https://user-images.githubusercontent.com/122295421/225904956-f2cfd51f-0244-4e6a-a9f0-4759d26f3977.png)

I was thinking that a possible strategy is to 'unwrap' the object from the supplier, then rewrap it again in Maybe<T>, but then get() has private access.. what is the way to solve this?

**2. The flatMap method()**
From my understanding, the function returns a Maybe<? extends R>, and once again, that is not a subtype of Maybe<R> due to invariance. Is the strategy also to unwrap and then rewrap? 

If that is the whole strategy, how do we do that given that get() has private access? 

Just need a push in the right direction :-s

**Comment by hengbl** [comment]
Yes, you are right. We need to unwrap the T from the supplier then wrap it up in Maybe<T> because supplier.get() returns a Maybe<? extends T> which cannot be converted to Maybe<T> hence the error. I also faced a similar error whereby if I try to call Maybe.<T>of(supplier.get().value) there will be a compilation error. One way to circumvent this is to first assign supplier.get() to a new Maybe<? extends T> variable then push in .value of that variable in Maybe.<T>of which gives no error. You can do the same for flatMap. I'm not too sure myself why this works so hopefully someone can clear my doubt too...

**Comment by emmannyyy** [comment]
bruh thanks so much! I went to read up about what you've mentioned. 


So apparently, we cannot access private fields from instances themselves, but **can access them through "[reflection](https://www.programiz.com/java-programming/reflection)" **

Had a good read about this, will clarify with my TA!

**Comment by lershuan** [comment]
> Yes, you are right. We need to unwrap the T from the supplier then wrap it up in Maybe because supplier.get() returns a Maybe<? extends T> which cannot be converted to Maybe hence the error. I also faced a similar error whereby if I try to call Maybe.of(supplier.get().value) there will be a compilation error. One way to circumvent this is to first assign supplier.get() to a new Maybe<? extends T> variable then push in .value of that variable in Maybe.of which gives no error. You can do the same for flatMap. I'm not too sure myself why this works so hopefully someone can clear my doubt too...

Thanks! this was very helpful
