### ISSUE TITLE
lab 5.2 test case 12 (9_12)

### ISSUE THREAD

**Issue by tallkoh** [nus-cs2030/2223-s2#455]
# Summary

can't figure out what's wrong with my 9_12. i initially thought it's because I did not remove customer from self check queue properly but even after fixing the errors in output are still the same.

is anyone able to come out with a similar test case to the private test case so I can try to debug lol.....

<img width="866" alt="Screenshot 2023-03-19 at 11 43 26 AM" src="https://user-images.githubusercontent.com/74520346/226152354-c68eae47-8a72-4fb5-a2e5-af69f9d87709.png">

**Comment by fy17ohhh** [comment]
from the first error, seems like you did not implement self-checkout queue properly so that customer 163 leaves cuz the queue is full; can try come up with TC involving self-checkout queue and wait events at self-checkout counter

**Comment by littlemidget3** [comment]
perhaps you can try ensuring that whenever a self counter serves, you are removing from the first counter's queue and not the from any other counter
depending on your implementation of checking length of queue, whether its by an int qlength or q.size(), ensure that its reflects a change in the queue so that when customers arrive, they can join the queue
also check that u remove from queue in the right event

**Comment by tallkoh** [comment]
> from the first error, seems like you did not implement self-checkout queue properly so that customer 163 leaves cuz the queue is full; can try come up with TC involving self-checkout queue and wait events at self-checkout counter

could you elaborate a little more 🥲🥲😭

**Comment by fy17ohhh** [comment]
> > from the first error, seems like you did not implement self-checkout queue properly so that customer 163 leaves cuz the queue is full; can try come up with TC involving self-checkout queue and wait events at self-checkout counter
> 
> could you elaborate a little more 🥲🥲😭

i would suggest you to include print statements to print out the details of each event on top of pq(server of the event, queue num of the server, etc). they generate a test case with many self-checkout counters and customize customer arriving times so that customers need to wait at self-checkout queue to be served. Then see if your queue num is updated properly after each event.

**Comment by calvnleong** [comment]
You can try to print out the whole queue/queue length using a for loop for each self checkout counter, after an arrive, wait or serve event occurs. Maybe this can help u to see which event adds/removes customers wrongly. For tc, you can try using the last test case provided and change the number of selfcheckout counters and human servers (i think)

**Comment by yinshuennn** [comment]
Hi, could you elaborate on how you managed to solve this, currently facing the same prob as you.
