### ISSUE TITLE
Codecrunch error lab6

### ISSUE THREAD

**Issue by Blackknight25** [nus-cs2030/2223-s2#458]
My code runs just fine on vim but has codecrunch errors... even though i imported java.util.Optional for all files but my isPresent() and get() methods are not being accepted,,, any help is welcomed thankyou:,,,,

Screenshots (if any)![telegram-cloud-photo-size-5-6104981714603455976-y](https://user-images.githubusercontent.com/109853328/226158602-bf93b7f9-3fa3-4e21-a073-3813ff1038d8.jpg)

**Comment by JYeoZS** [comment]
Dun think those methods recognised in code crunch. As mentioned in lab, get() used for debugging but not recommended for usage in code.

For get() why not use map, flatmap as front part of level 4.

For isPresent() there are other ways around it. See if getValue() helps. Then compare whether the values match.

P.s. may wanna use equal() when comparing instead of  ==.

**Comment by granolaluvr69** [comment]
I think similarly to exercise 4, the use of orElse() and map() might help.

**Comment by Huanqing-Mao** [comment]
Using get() or isEmpty() will break the abstraction barriers, so we should use orElse()
