### ISSUE TITLE
Lab 05 Test Case 9_03

### ISSUE THREAD

**Issue by shuyabeans** [nus-cs2030/2223-s2#487]
hi im not able to pass the test cases below, is anyone able to advice me on how to approach this? 

<img width="455" alt="image" src="https://user-images.githubusercontent.com/114815789/226317354-112d50af-c564-4c89-9ff8-6da4675bc4d0.png">

**Comment by ayevxn** [comment]
Looks like there might be an issue with how you call rest time, since in the expected output server 1 has some rest time in between 9 and 10 while server 2 does not have rest time between 8 and 12. In your output, server 1 does not have rest time but server 2 does. Are you potentially calling for rest time more than once per customer served, or maybe you are calling rest time in the wrong event? Maybe try to call rest time in done event instead of another if that is what you are doing right now.

**Comment by prisciliapangg** [comment]
I think you are not updating your serverList with updated timeFree (based on your output, your server is able to serve immediately without taking a break). If you have implemented your getRestTime() in your DoneEvent, I think you should check to see if you updated your serverList correctly

**Comment by stxe09** [comment]
where and when are you calling restTime?
