### ISSUE TITLE
Sequence of events Done --> Rest

### ISSUE THREAD

**Issue by tali-a** [nus-cs2030/2223-s2#498]
Hello! I am a bit confused about the sequence of events from Done -> Rest and where Rest transitions to. I generate  server's rest  time in done event and update the server's next  available time accordingly, and the done event returns itself if the server's rest  time is zero. i've checked that the service time is updated correctly in both done and rest  events, but  the rest  event returns itself, which means that updating the server list essentially has no effect. in that case, are we supposed to be transitioning to another type of event? like the wait event? and if i didnt use the intermediate wait event  approach previously, do i have to change it all  to include intermediate wait events ? thank you  very  much for any advice in advance

**Comment by prisciliapangg** [comment]
Hello! Actually, you do not need a Rest Event if you are already generating your restTime in the DoneEvent. Also, it may be different for you due to the difference in implementations, but I did not check if restTime is zero. Instead, I generated the restTime, updated the server with updatedFreeTime (zero or not), and updated the server list. This serverList will then be used for my nextEvent.

**Comment by hcyrr** [comment]
hello i think its up to your implementation, on other threads ive seen many people not needing a Rest event, i think they just update the server's next avail time in the Done event if the server needs to rest(?). for mine, if my server needs to rest, my done event returns a rest event, and then i update the server's next avail time in this rest event and update my server's isresting attribute to true. my rest event then returns another restend event, which only update the server's isresting attr to false. i do it this way just so that it is clearer for me, im sure there are much shorter/simpler ways to do so!

**Comment by xj8423** [comment]
hi! for me my done event generates rest time and a rest event, i use the rest event to update my server attributes (update his next available time and his isAvailable boolean etc). i did not have an end rest event, so my rest event just stops there, if that makes sense.. the purpose of my rest event is the update the server list, which i return as a pair from executing the event, so that future events can use this updated server list.  i dont think your rest event should return a wait event also because it might cause cyclic dependencies, im not very sure about this though! hope this helps :)

**Comment by SumDumPhuc** [comment]
Hi, I think you can try using a RestDone event to solve this issue. However, it may lead to cyclic dependencies so I suggest implementing it in the Done event instead.

**Comment by Aron113** [comment]
you can do add the rest time to the server in the Finished event

**Comment by guanquann** [comment]
I think it will be easier if you do not create a rest event. You simply need to update the timing of the server in your server list.

**Comment by maze508** [comment]
You can consider adding restTime as an argument to your previously defined classes/methods like @guanquann said.
