### ISSUE TITLE
Exercise 2 level 4 repeated output

### ISSUE THREAD

**Issue by j0205m** [nus-cs2030/2223-s2#55]
my code works fine in level 3 but when it comes to level 4 there's this repeated output only at one portion of the total output... i have tried debugging for hours but the same problem still occurs : ( i'm not sure which part of my implementation is wrong any help is much appreciated 

<img width="520" alt="Screenshot 2023-02-03 at 03 17 35" src="https://user-images.githubusercontent.com/124303065/216428760-6b4dfd7a-4e87-4b49-a96e-43cba764b6a2.png">

**Comment by trwstin** [comment]
Could you briefly explain your logic so it might be easier for others to provide help?

It seems like you have also failed the final given test case in level 4, as shown below:

![Screenshot_2023-02-03-09-17-33-12_df198e732186825c8df26e3c5a10d7cd.jpg](https://user-images.githubusercontent.com/68576751/216487998-7e6ad4bc-52d1-4ed5-b427-29398be0a7a3.jpg)


Since you said level 3 works as expected, perhaps you can create a similar test case but without the use of the subclasses Big/SmallCruise? The idea is to test if your implementation for level 3 is actually correct.

Your cruises in this test case should use the same amount of loaders and arrival/service time as the respective Big/Small cruises in the level 4 test case above. Just do the calculations using the values given, then manually input them when creating the Cruise object.

If your output is correct, then the problem might lie in your implementation of the subclasses.

If it's still wrong, then something with how you manage the queues might be incorrect.

**Comment by j0205m** [comment]
> Could you briefly explain your logic so it might be easier for others to provide help?
> 
> It seems like you have also failed the final given test case in level 4, as shown below:
> 
> ![Screenshot_2023-02-03-09-17-33-12_df198e732186825c8df26e3c5a10d7cd.jpg](https://user-images.githubusercontent.com/68576751/216487998-7e6ad4bc-52d1-4ed5-b427-29398be0a7a3.jpg)
> 
> Since you said level 3 works as expected, perhaps you can create a similar test case but without the use of the subclasses Big/SmallCruise? The idea is to test if your implementation for level 3 is actually correct.
> 
> Your cruises in this test case should use the same amount of loaders and arrival/service time as the respective Big/Small cruises in the level 4 test case above. Just do the calculations using the values given, then manually input them when creating the Cruise object.
> 
> If your output is correct, then the problem might lie in your implementation of the subclasses.
> 
> If it's still wrong, then something with how you manage the queues might be incorrect.

Hi thank you for your suggestion! i have tried retesting with Cruise but it gives the same error so i'm guessing the error lies in the implementation of level3.jsh file. In the serveCruises() method I have used the remove() function while iterating through the expiredServiceQueue (in order to "transfer" to activeServiceQueue), so the length of the expiredServiceQueue is modified during the iteration. However I'm not sure if this is allowed and will this pose an issue to the queue system?

**Comment by SimonSeeYongsheng** [comment]
> my code works fine in level 3 but when it comes to level 4 there's this repeated output only at one portion of the total output... i have tried debugging for hours but the same problem still occurs : ( i'm not sure which part of my implementation is wrong any help is much appreciated
> 
> <img alt="Screenshot 2023-02-03 at 03 17 35" width="520" src="https://user-images.githubusercontent.com/124303065/216428760-6b4dfd7a-4e87-4b49-a96e-43cba764b6a2.png">

Maybe you can take a look at https://github.com/nus-cs2030/2223-s2/issues/46

**Comment by trwstin** [comment]
> Hi thank you for your suggestion! i have tried retesting with Cruise but it gives the same error so i'm guessing the error lies in the implementation of level3.jsh file. In the serveCruises() method I have used the remove() function while iterating through the expiredServiceQueue (in order to "transfer" to activeServiceQueue), so the length of the expiredServiceQueue is modified during the iteration. However I'm not sure if this is allowed and will this pose an issue to the queue system?

I cannot say if it's a good practice, but I also modified the queues during iteration and it worked out. 

Are you handling your services exclusively in Active and Expired? I found it useful to have a separate list that keeps track of all the added services. 

This lets me add/remove from the respective lists without worrying about the change in order of elements, which may affect the final result.

**Comment by syafiq9326** [comment]
Hi may I know what approach you took to solve it? As I am facing the exact same issue
