### ISSUE TITLE
Lab 6 Level 1

### ISSUE THREAD

**Issue by allnotavailable** [nus-cs2030/2223-s2#601]
Hi does anyone have any idea why my first assessment is not listed into the ImMap?
<img width="582" alt="Screenshot 2023-03-25 at 9 04 57 PM" src="https://user-images.githubusercontent.com/125998537/227718928-4bf43434-9bae-42db-a2a2-a034d470b11f.png">

**Comment by coderlimjingcheng** [comment]
How did you implement your Module class and its put method?

**Comment by lynettelcl** [comment]
how does ur Module class look like? then can debug

**Comment by junhonglow** [comment]
The data structure that is being used here is a map where each key can only be mapped to a single value. 
When you call put(new Assessment("Lab1", "A"), the key is "Lab1", and since it already exists in the map, it's original Assessment is replaced with the new Assessment you just created, as reflected in the second output statement.

**Comment by allnotavailable** [comment]
> The data structure that is being used here is a map where each key can only be mapped to a single value.
> When you call put(new Assessment("Lab1", "A"), the key is "Lab1", and since it already exists in the map, it's original Assessment is replaced with the new Assessment you just created, as reflected in the second output statement.

ah yes i changed and it works. Thank you.
