### ISSUE TITLE
Issues for updating the Servers ImList

### ISSUE THREAD

**Issue by kayeugenia** [nus-cs2030/2223-s2#61]
I have an issue to update the Servers ImList

I am not sure if I should update it in the child classes, but that will not update the actual servers ImList? I think the tips given told us to update in Serve.java but how can i ensure that when the next Customer arrives, the servers ImList will be the updated one?

**Comment by poon-zx** [comment]
i think you can try updating it in the method that you are calling in the event classes by putting it in the input of the method, so this ensures that everytime you call the method, you can pass in a list of servers and also return the new updated list of servers

**Comment by e0959170** [comment]
for methods in the classes i guess if you add the imList in the paramter and return the imList in the method and reassign it back in the main then it would update? like ImList<Server> sList = customer.doSomething(sList,…..) but i’ve not tried that before haha

or you could have a method in the simulation class (or wherever u initiate the list) which sole purpose is to update the serverList instead? not sure if it’s best practice to do it in the class itself

**Comment by kayeugenia** [comment]
@e0959170 i think the first method doesnt work bcs the list is private final?

**Comment by e0959170** [comment]
oh i see... if you have a private final ImList in let's say in the Customer class or something, it would be tough to update since you would probably have to make an entire new Customer object with all the existing data and the updatedList

**Comment by 0liverkong** [comment]
i recommend just keeping a local ImList in Simulator.simulate. you shouldnt need it beyond that scope anyway.

**Comment by granolaluvr69** [comment]
Just create a method in each event type that returns a new server object with the correct server state set.

Implement a method in the simulate class to replace the server with the outdated server object with the updated server object.

After that, for every iteration of polling pq, pass the server list and the server into your helper method to update it.

You might also want to pass your server list into the events in order to check for the index of the next free server, so it can return a new server object with the right index.

Hope I helped!

**Comment by kayeugenia** [comment]
@granolaluvr69 yup thankss! i ended up passing my servers ImList to the events and it worked
