### ISSUE TITLE
Lab 5.2

### ISSUE THREAD

**Issue by sp4ce-cowboy** [nus-cs2030/2223-s2#626]
Hi, for Lab 5.2,  I can't seem to understand how exactly the Self-Check is supposed to work, and what is meant by "all Self-checkouts share the same queue"

1) Does that mean that, there is a singular queue whose size is the sum of all the qmax for each self-checkout? 

2) For e.g for 2 self-checkouts and qmax of 1, If a customer were to arrive and wait at self-checkout 1, another customer who arrives will wait "at" self-checkout 1 even though he is actually waiting at self-checkout 2? How would I get the same customer to "wait" at self-checkout 1 without exceeding the qmax? 

3) If the qmax was 1 and there are 2 self-checkouts, does this mean that only 1 customer is allowed to wait at the self-checkout queue even though there are 2 self-checkouts? In what circumstance then would a customer arrive and leave because the self-checkouts are "full"?

**Comment by weitatftw** [comment]
1. it means that all self checkout counters share a single queue and that for every customer that queues at the self checkout counter you would need to increment the number of customers queueing at all self checkout counters by one. to visualise this you can imagine queueing to use a self checkout counter at NTUC.

2. honestly depends on your implementation of self checkout. you could either create a single self checkout counter manager that handles all self checkout counters and ensures that all customers are enqueued into a single queue or you can create multiple self checkout counters and you would have to increment the number of customers queueing at all self checkout counters if you find one customer being enqueued into a self checkout counter and the same goes for when you serve a customer.

3. yes. for example, if your self checkout counters have a qmax of 1, if a customer arrives, it will first check whether your human servers can serve them / can be enqueued there or not. if they can't be enqueued at the human servers, they would check whether any self checkout counter can serve them or not. if not, then they will check the single queue for all. if there's one person in the queue, they would leave the shop since enqueueing them would cause the number of customers queueing at that single queue to be greater than qmax. otherwise they would queue within the single queue for all self checkout counters.

**Comment by hcyrr** [comment]
all self checkouts share the same queue means that lets say each of your self checkout implementation has a imlist/pq of customers right, then this imlist/pq of customers is the same for all self checkouts
for "For e.g for 2 self-checkouts and qmax of 1, If a customer were to arrive and wait at self-checkout 1, another customer who arrives will wait "at" self-checkout 1 even though he is actually waiting at self-checkout 2? How would I get the same customer to "wait" at self-checkout 1 without exceeding the qmax?" u dont actually need to get the customer to wait at self check 1 even though he is waiting at self check 2, it is just that even though the customer is rlly waiting at self check 2, it is printed that the customer is waiting at self check 1.
