### ISSUE TITLE
Lab 07 Qns 1

### ISSUE THREAD

**Issue by DavidLawCheng** [nus-cs2030/2223-s2#636]
# Summary

Description of the question / problem here.

## Description:

How do you link the first of(T t) method with the second of(T t, String Log)?

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by edwinhrj** [comment]
hmm im not sure what you meant specifically by that query. However, I did face some problems in formatting my Log class in lab7 level 1 as well due to the restrictions in checking for null. 

maybe you can try working along the lines of the logic of returning a T object, as well as an empty string in the of(T t) method in Log? So this "connects" the of(T t) and the of(T t, String string) methods of Log. Hope this helps!

**Comment by DavidLawCheng** [comment]
Oh okok thanks a lot!
