### ISSUE TITLE
Ex 5 Level 4 IndexOutOfBounds 

### ISSUE THREAD

**Issue by Delocy** [nus-cs2030/2223-s2#637]
IDG why im getting index out of bounds when i specified in my condition that the x must be within the size of the list.
<img width="713" alt="Screenshot 2023-03-27 at 10 49 34 PM" src="https://user-images.githubusercontent.com/94375191/227976760-b91271b0-525d-48ca-a12c-a5cf0870f706.png">
![Uploading Screenshot 2023-03-27 at 10.52.17 PM.png…]()

**Comment by hengbl** [comment]
What you wrote seems to suggest that if x == 0, you will encounter the error at this part of your code:
x < list.size() && list.get(x - 1) == 0 

When you hit this part because 0 is lesser than list.size() it will try and get x - 1 which will be out of bound. You need to specifically account for when x == 0 and x == list.size() - 1 because in these two cases, you only check the value to the right and left respectively.

**Comment by jaejayrome** [comment]
the issue comes from the fact that you put list.get(x + 1), this doesn't account for the fact that if x is list.size() - 1, that would mean that you are trying to get a list.get(x = list.size()), which would definitely throw an indexoutofbounds exception
