### ISSUE TITLE
Filter method in Log

### ISSUE THREAD

**Issue by alvintjw** [nus-cs2030/2223-s2#638]
# Summary
If null is not allowed in this lab, what should I return for values that doesn't pass the predicate.test()
Description of the question / problem here.

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by jaejayrome** [comment]
sorry I don't get ur question, the lab doesn't ask us to make a filter method for our Log class. With regards to predicate.test(), ensure that the lambda function passed in returns a boolean value that's all. hope this helps!

**Comment by emmannyyy** [comment]
The filter function can be used to guarantee that there **are valid arguments** in your constructor.  

If the arguments aren't valid, your Optional will create an optional empty. This is ideal because if that happens, your orElseThrow() method can then be used to throw the illegalArgumentException error. 

Just a little tip for checking if the values are 'null' 
-> the predicate to test for value should just check if the value is **instanceof** Log<?>. Note that this automatically tests for nullity, so you only need this predicate
-> the predicate to test for whether the input string is even null can just be `() -> true`. 

Just work on ensuring that you run these tests when solving lvl 1

**Comment by andersooi** [comment]
For the filter function, I just pass in a check to filter out anything that is not an instance of Log

**Comment by shannon-jx** [comment]
use Optional.ofNullable() to identify null values of t, use filter to check if the argument is an input of Log, can also use flatMap to check if String log is null by returning Optional.ofNullable(log). then u eventually flatMap the whole thing to return you your new Log + orElseThrow(). remember to put in a Supplier argument for orElseThrow to get the desired output as stated in the question. use java api to help u!
