### ISSUE TITLE
Lab 7 testcase 2_1

### ISSUE THREAD

**Issue by dorislaiii** [nus-cs2030/2223-s2#688]
# Summary

Hello, I'm facing this problem with test case 2_1. How can I fix this?

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)
![Screenshot 2023-04-01 at 12 19 52 PM](https://user-images.githubusercontent.com/125382804/229265383-3509c095-1890-4c8d-bbe5-d3a95d71f87d.png)

**Comment by jaejayrome** [comment]
I suspect that your mistake lies within the map() method in ur Log class, here they are trying to test by passing in a function that takes in a type A and returns a type C, ensure that when you define the map method in your implementation, the return type of the Function should be (? extends R), since your map is producing something when it's returning by convention of PECS(producer extends consumer super).

**Comment by Yihao2001** [comment]
likely is something wrong with your map class might want to check it

**Comment by Ernestnzx** [comment]
It's most likely going to be for function not having the appropriate wildcards! As what jaejayrome mentioned your function's wildcard should be something like this.

`Function<? super T, ? extends R> mapper`

Hope this helps!

**Comment by dorislaiii** [comment]
okie fixed it. thank you!
