### ISSUE TITLE
Do we need to import java.util.Comparator?

### ISSUE THREAD

**Issue by SimonSeeYongsheng** [nus-cs2030/2223-s2#69]
# Summary

Guys, my TA told me during lab that the java.util.* is automatically imported into vim, if you used docker.
But I faced a compilation error when compiling a class that implements a Comparator.

Do we need to import the Comparator class for this lab?

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by joshuagohez** [comment]
Faced the same issue whereby java could not recognise the PQ class that implemented Comparator unless we explicitly write the import statement `java.util.Comparator`. Checked in jshell with /imports and it shows that java.util.* is already imported(?). Weird.

**Comment by EpicSpirito** [comment]
Same issue, I just import ` java.util.Comparator` and it worked.

**Comment by LYEDominic** [comment]
I also faced this same issue, ended up importing java.util.Comparator into my comparator class.

**Comment by danqiye1** [comment]
Hmmm it is not true that java.util.* is automatically imported into vim. Firstly, vim is just a text editor so it doesn't import anything. Jshell, on the other hand, imports java.util.*, so you can create List, ArrayList, Comparator, etc. However, if you try to open an external java source file in jshell, you need to write the necessary import statements in the source files so that the class can be compiled.

**Comment by SimonSeeYongsheng** [comment]
> 

I see, thanks for the clarification!
