### ISSUE TITLE
Lab 7 Level 4 Test Case 4 Error

### ISSUE THREAD

**Issue by kcslllll** [nus-cs2030/2223-s2#705]
# Summary

hi! does anyone know how to fix this issue? for my flatmap method, there is a "\n" between the log and flatmap's result's log, but when i remove it, the 3 lines will be correct in the snippet below but my level 3 will fail (the output will be all on the same line instead of being on the next line). thanks alot! :)

## Screenshots

![image](https://user-images.githubusercontent.com/122248706/229303881-ec64a0d0-eb5e-4785-84c4-3f281ae5eca3.png)

**Comment by Chuacx13** [comment]
check whether your initial log is empty string or not empty string, then add the \n where appropriate

**Comment by wjkb** [comment]
use a if-else statement so eg. if (this.log == ""), no need to \n

**Comment by aeraeroaer** [comment]
you can also use the inbuilt String isEmpty() method

**Comment by Ernestnzx** [comment]
Not sure if this is relevant to the problem, but when you are comparing classes / generic types, never ever use `==` because you are comparing the address value of the objects (which almost all of the time is not the same). Instead you should be using the class's `.equals()` method this ensures that we are comparing the underlying value instead of the addresses.

Hope this helps :)

**Comment by leonardwx** [comment]
you could check the this.log.isEmpty() ? "" : "\n" + this.log

**Comment by e0969794** [comment]
this is because this.log has an empty string in the test cases given. when concatenated with the /n, it puts the output on another line. use a logic to check whether this.log has an empty string or not before using /n! you might want to check if other.log has an empty string as well to prevent any errors. hope this helps!

**Comment by ouhznay** [comment]
maybe can try checking ur flatmap method if you are accounting for cases where the log is empty bcos the method may print additional empty lines that is unecessary

**Comment by kcslllll** [comment]
thank you all! :)
