### ISSUE TITLE
Implementation of serverList

### ISSUE THREAD

**Issue by chianxintong** [nus-cs2030/2223-s2#727]
# Summary

I am thinking of having 3 classes: Server (abstract class), HumanServer, SelfCheckout, where HumanServer and SelfCheckout extend Server.

In each event, i have a next() mtd which takes in a serverlist and loops through it to return (e.g. an available server for ArriveEvent).
If my implementation of serverlist is ImList < Server > , i would not be able to make use of the method .getRestTime() which is unique to HumanServer, and .getListofSelfCheckout() which is unique to SelfCheckout. 

May I have some hints on how i can go about implementing serverList? Would it be advisable for me to represent serverlist as 
Pair < ImList < HumanServer > , ImList < SelfCheckout > > ? 

EDIT: Wouldn't there be cyclic dependency if my SelfCheckout extends Server, and in Server, there is an abstract method that returns ImList<SelfCheckout> ? (for getting list of self checkout counters)

**Comment by sethteo** [comment]
If my implementation of serverlist is ImList < Server > , i would not be able to make use of the method .getRestTime() which is unique to HumanServer, and .getListofSelfCheckout() which is unique to SelfCheckout.
> 
the getRestTime() method can be overriden to call the supplier.get() if its a Human server and return 0.0 if its a SelfCheckOut

**Comment by chianxintong** [comment]
@trwstin @sethteo HmMM wouldnt there by cyclic dependency if getListofSelfCheckout() is common for both?

selfcheckout extends server, server has an abstract mtd which returns an imlist of selfcheckout

**Comment by sethteo** [comment]
> @trwstin @sethteo HmMM wouldnt there by cyclic dependency if getListofSelfCheckout() is common for both?
> 
> selfcheckout extends server, server has an abstract mtd which returns an imlist of selfcheckout

Since selfcheckout extends server, the abstract mtd can return a list of server so theres no cyclic

**Comment by gracico** [comment]
kudos to the implementation of a new abstract class. I had the same idea initially but i eventually went ahead to extend my server instead so its less confusing. 

as for your worries on cyclic dependencies, maybe instead of having a selfcheckout returning a list of checkouts, you could have another class - a manager which returns the selfcheckouts 

with a manager should be able to handle the editing of the imList with better abstraction

**Comment by kyledilao777** [comment]
i think the most straightforward way would be to use serverList as an ImList of servers which contain server, selfcheckout (subclass of server).

**Comment by sp4ce-cowboy** [comment]
In my implementation, my Self-Checkout extends Server but my Server class also has an instance boolean called selfcheck which is set to true if the Server is a Self-Checkout and false if the Server is a Self-Checkout. This is done at the point of creation of any Server (or Self-Checkout) object. In my Server class's toString method there is a boolean check to return either this.serverId or "self-check" + this.serverId.

If you have a boolean indicator in your Server abstract class i.e. to indicate if this server object is Human or Self-Checkout, each Server object can be queried for this boolean (i.e. isSelfCheck()) after which the object retrieved from the Server list can be typecasted to a SelfCheck.

`ImList<Server> list = ...`
`SelfCheck temp = (SelfCheck) list.get(0)`
`temp.getListOfSelfCheckOut`

However take that with a pinch of salt because I'm not sure if explicit typecasting might be a design violation. Instead, you just include a dummy method `.getListOfSelfCheckout()` in the abstract Server class to return an empty ImList and override that in the Self-Checkout class. Later on in your code, you can use the boolean to check if the Server is a Self-Checkout if it is, invoke the `.getListofSelfCheckout()` method.

You can use .getRestTime() method by including `private static final <Supplier> Double ZERO_REST= () -> 0.0` in your Self-Checkout class (or create a new ZeroRestTime class that is the same as DefaultServiceTime) which creates a dummy Supplier (for each Self-Checkout) and this would ensure that you can put Supplier<Double> restTime field in your abstract class as now both the Servers and the Self-Checkouts would have Supplier restTimes.

**Comment by aowz** [comment]
You can implement .getRestTime() and getListOfSelfCheckout() as methods in all classes. The only change that needs to be made is the implementation of the method. getRestTime() can return 0 for SelfCheckoutServer and vice versa. This allows the methods to be called even though the variable is bonded to Server class. Hope this helps!

**Comment by chianxintong** [comment]
Hi all!! Thanks for your help :) i managed to solve it by returning 0.0 as restTime for selfcheckout

@aowz @sp4ce-cowboy @kyledilao777 @gracico @sethteo @aeraeroaer @trwstin @yugan01
