### ISSUE TITLE
Test Case 11 - selfcheckout | Lab 5.2 

### ISSUE THREAD

**Issue by niclee1219** [nus-cs2030/2223-s2#752]
# Summary

not sure where i can go about to change my code. seems to be arising from done --> serve next customer

## Description:

Clarifications or details with respect to the issue you are facing
<img width="664" alt="Screenshot 2023-04-05 at 4 21 06 PM" src="https://user-images.githubusercontent.com/20497341/230023854-3407cfac-8d8e-4735-ad7f-009f55e42ea7.png">

Thanks!

**Comment by sethteo** [comment]
are you ensuring that the self-check out that is passed to a serve is the earliest one, as I faced the same error before. because even though a customer always queues at k+1 it does not necessarily have to be served by k+1 instead you have to loop through all self-check outs and serve the customer with the self-checkout with earliest avail time :)

**Comment by vanessakohh** [comment]
yep i agree w sethteo. it seems like youre assigning a self-checkout server to a customer. this causes the customer to keep waiting for that specific counter when it should be served by the next available checkout counter. that should be what is throwing your results off right now.

**Comment by Cfyjdfk** [comment]
yup, everyting seth said

**Comment by hcyrr** [comment]
^^ yep! what worked for me was each time a wait event for a customer waiting a self check is polled, i loop through the self checks to get the self check with the earliest avail time/is free.

**Comment by keshialimm** [comment]
I faced this issue too, and it was because I didn't check to assign the earliest available self check to the customer. We have to make sure to do this in the wait/ intermediate wait events as well!

**Comment by sp4ce-cowboy** [comment]
Yeah the issue seems to be the self-checkout counter not being "seen" as available by the customers waiting in the self-checkout queue. You can see in line 32 where self-check 4 is done serving but in the rest of the output no customers are being served by self-checkout 4 even thought 4 is free (and has 0 rest time). In your relevant wait events, you can try iterating through the self-checkouts, and find the earliest available next available time for the self-checkout server with

<img width="465" alt="image" src="https://user-images.githubusercontent.com/19762596/230143843-a621f6a5-61d4-4644-9177-737a8575ba40.png">

or something like this. Also additionally, while this wasn't mentioned in the lab, if another self-checkout has the exact same next free time then the customer will remain at the same self-checkout, the next free time _has_ to be less, as you can see with the if statement. The isSelf() boolean returns a boolean true if the Server is a self-checkout (in my implementation).

**Comment by aowz** [comment]
I encountered this issue previously, it was because I wasn't allocating the earliest available self-checkout server. You need to implement a loop to check through which selfcheckout server u want to assign to serve for the serve event. Hope this helps

**Comment by jiangen16** [comment]
In my wait class, i checked if the server id is = k+1, if so it means the customer is waiting for the self check out servers. Thereafter, I used a loop to loop through all the self check out servers to look for the one with the earliest next available time, and assign that server to the customer. 

I know of others who used a comparator to look for the earliest available server amongst the self checks, maybe that will be easier for you too!

**Comment by Aron113** [comment]
you can try looping through the serverlist to update the queue whenever an event arises. i think that's why your customer leaves instead of joining the queue

**Comment by niclee1219** [comment]
<img width="664" alt="Screenshot 2023-04-07 at 5 29 43 PM" src="https://user-images.githubusercontent.com/20497341/230584374-3340ac84-4f4a-47bc-b223-63ce4b806ebd.png">
thanks for all the input! my new error message seems to be because of a time issue, any idea how I should go about this?

**Comment by edmundnwl** [comment]
customer 13 is not waiting correctly, he should have checked that self-checkout 4 was done serving, instead he waited until self-checkout 3 was available.

**Comment by ahndrayo00** [comment]
This boggled me for days too LOL but like what others said, wrong allocation of customers to selfCheck.

You can try modifying 4.in to add more customers arriving while all servers are still serving. This will cause them to queue. Then you monitor how they go to which server (that's how I identified the problem).

Try creating a for loop to iterate through all SelfChecks to find fastest available SelfCheck then allocate the customer to that SelfCheck by creating the respective nextEvent

All the best!!

**Comment by niclee1219** [comment]
thanks all! this could be an issue of allocation of customers to the right checkouts. 

if anyone is still stuck on this, some tips:
- Print out ur pq to see where it gone wrong
- try using chatgpt to debug
- your issue will most probably lie in ur interimwait.java / serve.java. make sure the logic is correct on how u process. u should also check that the customer u are serving is the one at the front of the queue by using a custlist.get(0).getid==c.getid 

thanks @Aron113 for pointing me in the right direction!
