### ISSUE TITLE
Lab 5.2 Time Limit Exceeded 9_11

### ISSUE THREAD

**Issue by ahndrayo00** [nus-cs2030/2223-s2#754]
# Summary
How do I ensure all self-checkout counters share the same queue?
Description of the question / problem here.

## Description:
Currently, everytime I need to update queue, I first
1. check if the server is a SelfCheck or HumanServer
2. If it is a SelfCheck, I iterate through the serverList for all SelfCheck and update their queues. (Screenshot below)
3. If it is a HumanServer, I update only his queue.

However, this seems to be causing me time limit exceeding issues (although I seem to notice that others in the forum has also been doing this). Please if anyone could provide guidance on a better design for sharing the same queue and advise on what I'm doing wrong?

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots
![image](https://user-images.githubusercontent.com/123559896/230035637-ed2cbadc-41de-46d6-b2b6-91c694f71c3c.png)
![image](https://user-images.githubusercontent.com/123559896/230036571-2b09a5a5-46df-44ea-bad6-4a117e7bb0ca.png)

Screenshots (if any)

**Comment by Jahhlen** [comment]
Not sure what the issue is but they did say to avoid using Booleans to differentiate between classes (self-checkout or human server) as it is bad design? You might want to change to a design that utilizes polymorphism.

**Comment by jiarui22** [comment]
Time limit exceeds error always happen when you have the same event being returned again and again. For me, I only have queue for self checkout at the first self checkout counter. But I also think your design is ok. You may check if you have updated your server list and time properly in your wait, waitagain and other event class.

**Comment by notsushiii** [comment]
Perhaps you can try checking if there is an infinite loop somewhere in your code? The logic of the code chunk that you posted seems correct! As for me, I used one ImList of Integers to keep track of the queues for all human servers and the self-check counters as a whole.

**Comment by sp4ce-cowboy** [comment]
> Not sure what the issue is but they did say to avoid using Booleans to differentiate between classes (self-checkout or human server) as it is bad design? You might want to change to a design that utilizes polymorphism.

I think the explicit differentiation between classes is only considered bad design for Event Classes, i.e. overriding "getEventType" method  in each class to determine what event to execute next, as the next event generation process should be independent of event type. For Servers & Self-Checkouts, if the Server class itself has a boolean property indicating if it is a self-checkout or not (which is what I did) is not considered a violation of OOP design principles, as Servers and Self-Checkouts behave sufficiently differently (bc of the difference in queueing mechanism) that it would be quite difficult to utilize polymorphism for this aspect. Either way, CodeCrunch will not accept your submission if your code fails a private design test case, 

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/19762596/230090975-83d99121-3262-4d73-bf35-0e6330364c69.png">
so if you made it to the test cases already then it should mean that your design is fine.



@ahndrayo00 Answering the question, in this part of your code:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/19762596/230089404-b578f09e-9ead-4f9c-b48a-d9734200d3ba.png">

I'm not sure what the `.getHumans()` method does but I suspect that the for loop might be adding the customer to queues of all servers in the server list instead of only self-checkouts. From my understanding, the boolean `if (selfcheck)` first determines if the associated server is a self-checkout (?), and then loops through the server list, but doesn't check if that particular server iteration is a self-checkout. You can try having the boolean inside of the for loop, where each server in the server list is iterated through and then a `if (selfcheck)` boolean determines if the server is a self-checkout then carry on with the queuing process, else if the server is a human server then continue with the iteration. (I assume your self-checkout class extends Server). But I'm also not too sure because it also depends on the rest of your code, so if everything else seems fine you can try this out, I had some issues with my queuing as well and the faulty queuing mechanism might cause an infinite loop which would result in the time limit being exceeded.

**Comment by hcyrr** [comment]
my implementation is the same as urs so i think ur implementation is fine, u might have a infinite loop, u can check by making print statements in the simulator to see whats the event thats continuously being returned and then debug from there

**Comment by ahndrayo00** [comment]
Update: Am the OP here! I finally diagnosed the root cause of this issue. For me, it wasn't an infinity loop, nor was it a failure in updating all queues.

The reason was because while I was updating all queues, the Wait, Waiting and Serve events were still created based on the k+1 SelfCheck instead of the SelfCheck with the fastest freeTime. So for e.g, if I had 3 SelfCheck counters, and a queue of 10 people, all 10 people were waiting to get served by the first SelfCheck counter instead of being distributed among the 3 SelfCheck counters.

If anyone has the same issue, I managed to debug thanks to the help of the great people here! You can check out my other forum question with the logic of the solution written here: https://github.com/nus-cs2030/2223-s2/issues/762
