### ISSUE TITLE
5.2 test case 14

### ISSUE THREAD

**Issue by joelgoh1** [nus-cs2030/2223-s2#757]
# Summary

Getting the rest time and service times seems to be wrong

## Description:

In previous test cases, it seems to be working fine. However, I am getting incorrect get rest times and service times for test case 14. 

## Screenshots
![image](https://user-images.githubusercontent.com/64695851/230122423-f64c67d2-f0f0-44c2-a849-1826b93de336.png)

**Comment by sp4ce-cowboy** [comment]
It looks like 7 is being served immediately once 6 is done serving (instead of resting, at like 58-59), which means that the server rest time might not be added immediately after the server is done serving. In which part of your code are you invoking rest time? In my implementation, the nextEvent method returns Pair<Event, ImList<Server>> and when my DoneEvent generates the nextEvent, it returns itself but also updates the server by adding the rest time to that particular server's nextFree time and then returning the serverList. 

I also noticed that in line 60 and line 61 of the expected output, the service time for 7 is less than 0.001, 7 is served at 7.909 but also done serving at 7.909. But in your output, 7 is served at 6.305 and done at 6.306. Are you rounding up or down any of the time values in your code that might cause an extra 0.001s to be added to the time?

**Comment by joelgoh1** [comment]
Thank you! Yup, I'm implementing my rest time in the same way as yours with my done returning itself and updating the serverlist. I also noticed the service time, which is weird because I'm not doing any rounding.

**Comment by tjdbryan** [comment]
Is your SelfCheck calling anything from the Supplier? Also is your .get() called more than once?

**Comment by joelgoh1** [comment]
I fixed the issue! My self check didn't call anything from supplier, but my waiting implementation was incorrect so the serve was happening too early and I think that caused the other values to be incorrect. Thank you.
