### ISSUE TITLE
Lab 5.2 Test Case 9_11 exception in thread...

### ISSUE THREAD

**Issue by ngshiyingg** [nus-cs2030/2223-s2#767]
# Summary
Hi! Did anyone face a similar issue before? 
any help would be appreciated, thanks! 

# Description 
(I have server, selfcheckout that has an imlist of counters. both selfcheckout and counter extend server. )
I have checked that numofservers and numofselfchecks are non-zero in simulator class. 

# Screenshot 
<img width="1234" alt="Screenshot 2023-04-06 at 6 11 39 PM" src="https://user-images.githubusercontent.com/122260950/230347078-fce53d8b-a3c2-413c-a031-1cabeff3f54f.png">

**Comment by sp4ce-cowboy** [comment]
Yeah I faced the same exception before, this usually happens with list iterations. Essentially you are trying to `.get()` with an index larger (or smaller) than the size of the ImList (line 7). You can trace back the exceptions to debug. Main line 38 → Simulator line 67 → Arrival line 17 → Server line 22 → SelfCheckout line 14 → line 21 → ImList get method. This is the order of the exception being thrown, so it seems like the root problem is in your Arrival/Server/SelfCheckout classes, and somewhere here some list iteration process is faulty, possibly due to a wrong list index being provided.

**Comment by sjcze** [comment]
Specifically, for Index 0 out of bounds for length 0, this means that you are trying to access an empty array. I think you could trace the code back and see if you have accidentally left any arrays empty.

**Comment by linha00** [comment]
One possible reason for this issue could be the way in which the server list was created. 
specially is the one with 0 human server and all self server, it might be due to when you are creating the list, you create the human server first but for this case there is none, so the list is empty. But when you are going to create the self servers, you are using last Human server to find get the next number but for this case the list is empty thus the error
![image](https://user-images.githubusercontent.com/110731318/230399824-495dcab3-4bd7-41f2-8ff7-7c118bb2c093.png)

**Comment by eunicel23** [comment]
for me, i had a serverlist with human and self checkout servers, and when i tried to get a self checkout when there isnt any, it will throw this error. so i just had an if statement to check if theres any self checkout counters before trying to get it!

**Comment by shawncch** [comment]
encountered this error as well, make sure your serverlist is updated correctly esp in your self checkout’s wait event

**Comment by pylfmty** [comment]
ImList which has zero elements inside but you call imList.get(0), so the index is out of bound

**Comment by easypzlemonsqueezy** [comment]
yup check for the base case of 0, if there are no available counters return something else instead of doing a .get(0)

**Comment by koojaylynn** [comment]
hello! for me, i had this error when i was trying to .get(0) from an empty queue. you can consider using !isEmpty() to counter this :)

**Comment by tjdbryan** [comment]
Are you removing items from your list? If yes, then this will happen when the list is empty. You can have a while loop to ensure that the code only runs when the list.isEmpty() is false.

**Comment by cinobunzz** [comment]
i had the same issue as well. i find that checking if the list is empty before calling the get() method helps

**Comment by ngshiyingg** [comment]
> One possible reason for this issue could be the way in which the server list was created. i have this problem before and is due to how i created the serverlist, specially is the one with 0 human server and all self server, it might be due to when you are creating the list, you create the human server first but for this case there is none, so the list is empty. But when you are going to create the self servers, you are using last Human server to find get the next number but for this case the list is empty thus the error

omg yes this was my issue, thanks a lot!!
