### ISSUE TITLE
Wait events stuck in infinite loop

### ISSUE THREAD

**Issue by klexoskai** [nus-cs2030/2223-s2#777]
# Summary
Wait event keeps getting returned without the timing updated so it keeps getting polled resulting in an infinite loop

## Description:
- I checked my server's .nextAvailTime() through printing (and it is updated)
so confused as to why when I create new Wait event the timing is not updated 

## Code Snippets
<img width="838" alt="image" src="https://user-images.githubusercontent.com/104553825/230543797-68def863-e578-47be-8384-56314b763690.png">

## Screenshots
![image](https://user-images.githubusercontent.com/104553825/230543663-9951494b-19b9-43a2-9787-ff10c1eb1cf6.png)

**Comment by dmidula** [comment]
Hi, I think the issue is that when you are returning a new Wait Event, you are taking in 'this.server.getAvailTime()' instead of currServer.getAvailTime() as currServer is the server that you are getting from the most updated serverList.

**Comment by Blackknight25** [comment]
Hi, maybe youre using the wrong server. instead of this.server, you can use serverList.get(your index)

this.server may not have the updated timing but your serverList may have the server with the updated timing

**Comment by hcyrr** [comment]
hi i think you need to get the updated server's next avail time! like what blackknight said u can use serverlist.get(server's index) to get ur server's updated next avail time

**Comment by AmanDesai34** [comment]
Yup, you would need to take in the sever from the list and not this.server as Blacknight rightly said

**Comment by sp4ce-cowboy** [comment]
The problem seems to be that you're return the wrong server and serverList. I'm not too sure about your implementation but for the ServeEvent, you should update the server by invoking the customer service time and updating the server's next free time, and then update serverlist with this server, and then return the new serverlist. But if you have implemented this somewhere else then it should be ok.

For the WaitEvent, you are using the associated server's next free time, which would always be the same, instead you should use the next free time of the server from the server list.

**Comment by Aron113** [comment]
check that the event that is being returned contains the correct Serverlist

**Comment by easypzlemonsqueezy** [comment]
it might have to do with your event time not getting updated correctly, thus resulting in an infinite loop

**Comment by klexoskai** [comment]
thanks so much for the help guys :') it worked after I
- changed to currServer.getAvailTime()
