### ISSUE TITLE
Issues with SelfCheck extending from Server

### ISSUE THREAD

**Issue by joshlimwe** [nus-cs2030/2223-s2#787]
# Summary

## Description:

My current implementation is that my SelfCheck class extends from humanServer class with the proper toString methods for each respective class, my serve event correctly outputs "serves by self-check 2", however once it gets to my done event, it outputs "done serving by 2", i think this is an issue with my selfCheck classes becoming a humanServer class in between my serve and done event, but how can i fix it, or is it recommended to just re-implement with HumanServer and SelfCheckout inheriting from one parent Server class? Thank you!

## Code Snippets

Attach code snippets (if any)

## Screenshots

<img width="194" alt="image" src="https://user-images.githubusercontent.com/125873745/230592581-d32fbcc0-44da-4a08-a4a5-f06d75f23507.png">

**Comment by andersooi** [comment]
I also faced the same issue when I was doing this. The problem was transiting from a Serve to Done event. I can't really remember where the problem was but I do remember using print statement to print out the server that I was using and eventually found out why it was using a Server instead of a SelfCheckout. Would recommend using print statements to check which server you are using and then trace back to the relevant lines. Hope that it helps.

**Comment by notsushiii** [comment]
I think it might be doable to continue with the current implementation/inheritance. I tried to identify whether a Server is a Human Server or a Self-Checkout Counter using the Server ID in the Done Event. Then I had different Strings for the different types of Server in the toString() of Done.

**Comment by tali-a** [comment]
i faced this issue too, because my server lists weren't being correctly updated between events (not updating the server list in any of the required events) made it such that a selfcheck class became a human server

**Comment by niclee1219** [comment]
hi! could be a issue of ur classes.

in my original implementation, the tostring refers to the serverid. while this works for servers, self check does not work.

workaround is to use servername, where serverid=servername for servers, and servername="self-check" + serverid for selfcheckout. this way, u don't need to run a checker in ur serve/done class if its a selfcheckout/server

**Comment by edmundnwl** [comment]
how are you constructing your toString methods? are the events adding "self check" for the self-checkouts or are you calling the toStrings of the Server involved?

**Comment by easypzlemonsqueezy** [comment]
you might need a checker to return either "" or "self-check " in either your events or your server/self checkouts, depending on your implementation!

**Comment by ahndrayo00** [comment]
I would recommend having an AbstractServer class then have HumanServer and SelfCheck as 2 separate classes inheriting from it (your 2nd suggested solution). It only makes sense that way (better design!)

Then you override the toString() methods in both classes, that way you dont have to worry about the words anymore!

All the best!

**Comment by tjdbryan** [comment]
This happens when you are 'creating' new Server instances when updating your Servers (because of immutability).

If you do this:
```
Server newServer = oldServer.update(...);
```
Then if the input is a SelfCheck, the output will still be a Server.

Hence, like what some have suggested above, you can do a check to see if it is a HumanServer or SelfCheck, and return the correct instance type.

**Comment by clarwen** [comment]
Make sure if your implementation involves creating a new Server, consider whether is could be a Self Check and create a new SelfCheck instead
