### ISSUE TITLE
exercise 5 task 4

### ISSUE THREAD

**Issue by normantan1** [nus-cs2030/2223-s2#796]
<img width="449" alt="image" src="https://user-images.githubusercontent.com/88649714/230631337-6fe1520c-28f0-4ea6-8372-8f6c121854a9.png">

does anyone know why the first and last column of my last row is missing a x, I did consider the first column and last column when mapping hence im unsure how this happened

**Comment by syafiq9326** [comment]
yo  i faced the same issue as you for the last column, I initially also thought that I already accounted for the mapping correctly but I realised it was due to my generateRule() not accounting for the position on the left of last col being 1 properly.

i was doing a list.get(list.size() - 1) when it would have been list.size() - 2 all along, not sure if you had a careless mistake like mine. 

maybe can double-check your condition for where the index is 0 or list.size() -1? (for those u **only** look on the right and left respectively and not left and right)

Hope this helps!

**Comment by normantan1** [comment]
> yo i faced the same issue as you for the last column, I initially also thought that I already accounted for the mapping correctly but I realised it was due to my generateRule() not accounting for the position on the left of last col being 1 properly.
> 
> i was doing a list.get(list.size() - 1) when it should have been list.size() - 2 all along, not sure if you had a careless mistake like mine.
> 
> maybe can double-check your condition for where the index is 0 or list.size() -1? (for those u **only** look on the right and left respectively and not left and right)
> 
> Hope this helps!

Thanks for the input sir
