### ISSUE TITLE
Lab 5 Test Case 9_11 Issue

### ISSUE THREAD

**Issue by kcre20** [nus-cs2030/2223-s2#802]
## Description:

Hi, does anyone know what the issue here might be? Thanks in advance :)

## Screenshots

Screenshots (if any)
<img width="657" alt="Screenshot 2023-04-08 at 1 54 09 AM" src="https://user-images.githubusercontent.com/123935580/230654867-3f24e8ce-aeff-4739-a4dd-89c189fe1e4b.png">

**Comment by Chuacx13** [comment]
did u check for the server that has the earliest available time in the Wait event? i suspect that's where u met with the error. 

From what i see, customer 13 stays with self check out 3 because the wait event called for the intermediate event immediately, which results in the intermediate event to have a time that allows it to be called only after self check out 3 is done serving.

**Comment by BreatheManually** [comment]
When self-check out is done serving, did you check if there is anyone in queue to serve?

**Comment by sushimakerr** [comment]
hi! The problem seems to be that customer 13 keeps waiting at self-check 3 until they are served instead of switching over to self-check 4 when self-check 4 was available. Maybe you can try checking your Wait class if you have gotten the fastest self-checkout (it has the earliest next avail time)? the customer can be served if cust's arrival time >= fastest server's next avail time

**Comment by leonardwx** [comment]
hi it seems like your self check availability time is incorrectly updated, try to get the earliest available time for self check during the wait event.

**Comment by kcre20** [comment]
thank you so much everyone! fixed, all your suggestions were helpful :)
