### ISSUE TITLE
Lab 5.2  Test Case 9_11

### ISSUE THREAD

**Issue by cher212** [nus-cs2030/2223-s2#814]
# Summary
Im not sure why customer 16 and 17 are served before 15.

## Code Snippets
This is currently my nextEvent method in PreServeEvent (buffer). According to other posts i have seen, I already removed customer at buffer instead of serveEvent. 
My customersList in Server is an integer of number of customers in the queue, so removing a customer just means decreasing the number by 1.
<img width="666" alt="image" src="https://user-images.githubusercontent.com/125173830/230709510-7fafb010-ad1d-492a-8e0f-9395cbd9df02.png">

## Screenshots
<img width="406" alt="image" src="https://user-images.githubusercontent.com/125173830/230709472-b6cda1c2-abe0-454e-b885-1a3f6f0803ad.png">

Screenshots (if any)

**Comment by weitatftw** [comment]
you may have implemented the common queue for the self checkout counters incorrectly as it appears that 15 is queueing at counter 14 when it should actually be waiting for the next available self checkout counter. you would need to loop through the list of self checkout counters to determine which counter is available first, and then have the customer be served by the first available self checkout counter

**Comment by UmpoDumpo** [comment]
Check out the previous threads on this test case! Many people got stuck on this test case including me and the most common error was that the earliest self checkout counter was not accounted for.

**Comment by cher212** [comment]
@UmpoDumpo other than wait event and buffer event, is there anywhere else the earliest selfcheckout should be accounted for?

**Comment by sp4ce-cowboy** [comment]
Yeah it seems like the problem has to do with getting the earliest available Self-checkout counter, you can refer to #762, there's a more detailed explanation.

![image](https://user-images.githubusercontent.com/19762596/230712991-2b3f14d8-a592-43b1-8e12-772a8e58314d.png)

In this line, i think you can try changing it to `i = numOfServers` instead of `i = numOfServers + 1`. If there are 4 servers (k) and 1 self-check, the first self-check would occur at index 4 (i.e. i = 4, list.get(i)) not 4 + 1.

In the part of your code where you determine the earliest available self-checkout, you can try initializing fastestNextAvail with the getNextAvailTime of the current Self-Checkout associated with the current Event. I'm not too sure why this is the case, it kind of doesn't make sense, but if the loop cannot find a faster available time than the current Self-Checkout (i.e. same next available time) then it should "default" to the existing Self-Check. I tried submitting without this and my code failed some test cases later on. It might just be because of some error in my implementation, but it's worth a try.

**Comment by cher212** [comment]
@sp4ce-cowboy Thank you so much for the reply, the problem was indeed solved with initialising fastestNextAvail with getNextAvailTime of current Self Checkout!
