### ISSUE TITLE
5.2 test case 11, calculating waiting times

### ISSUE THREAD

**Issue by tali-a** [nus-cs2030/2223-s2#817]
![image](https://user-images.githubusercontent.com/103631647/230715248-31517c0a-9dd9-49af-8803-b29dd2f8dea6.png)

has anyone faced a similar issue with calculating waiting times? i assigned a self checkout to a customer and event(based on earliest  available) in the execute method of my intermediate wait event, as well as the wait event. my waittimes are calculated in the intermediatewait  event with the difference between a server's next  service time and the customer's arrival time

**Comment by e0959170** [comment]
in your implementation do all the customers go to intermediate wait directly? if you're calculating it in intermediate wait but some customers go to wait without passing through intermediate wait, there could be some discrepancy. you could also check that you are not double counting the wait times on accident.

**Comment by sp4ce-cowboy** [comment]
You can try putting the waiting time calculations in the ServeEvent, by taking the difference between the ServeEvent's timeStamp and the customer's arrival time with super.getCustomer().getArrivalTime() or smth like that. This would mean that for customers that don't go through intermediateWait, i.e. Arrival → Serve, their time difference would automatically be 0 and added in the waiting time calculations. It also makes more sense this way, because you would only know the end of the waiting period when the customer eventually gets served, and since all customers who wait get served eventually, but not all customers who were served had to wait.

**Comment by tali-a** [comment]
thanks everyone for the advice!! in my implementation all customers go to intermediate wait immediately, and i did try the serve event method of calculating wait time, which wasnt really suitable for my implementation as i would "bring" customers up in my intermediate wait  event by updating their arrival times. instead of doing checkout selection in wait and waiting classes, i did it only in the waiting class, in the execute and updated wait time methods, which worked with my implementation
