### ISSUE TITLE
Lab 5.2 9_14

### ISSUE THREAD

**Issue by YanQin-Liu** [nus-cs2030/2223-s2#819]
Does anyone have the test case for 9_14?

I have an infinite loop going on in my code but I have no idea where it is and I have no way to debug my code

<img width="447" alt="Screenshot 2023-04-08 at 6 21 30 PM" src="https://user-images.githubusercontent.com/123805062/230716158-bd25ecf5-cb7c-4bd4-9bf9-2de72a8305dc.png">

I have passed all test cases without issues and I have absolutely no clue as to what is causing this issue

**Comment by sp4ce-cowboy** [comment]
Infinite loops are most like due to the same event being returned and added to the PQ, or the same customer being added back to a queue, you can start with debugging there. There have been quite a few infinite loop errors, you can try checking the previous threads. #661 #754 for e.g (can just search "infinite" or "infinite loop" in the search bar under the issues tab)

**Comment by justineeyx** [comment]
if u have implemented a buffer wait event, that is returning a serve event or itself , there might be an infinite loop there

**Comment by YanQin-Liu** [comment]
Issue solved in #822
