### ISSUE TITLE
Docker Keeps Crashing (AMD64 Error)

### ISSUE THREAD

**Issue by oofpouf** [nus-cs2030/2223-s2#823]
Hello! I got a new laptop (Macbook Pro with M2 Chip) recently, and downloaded the apple silicon version of docker. However, when I pulled the cs2030 image onto docker, the AMD64 warning label appears and there's the message "Image may have poor performance, or fail, if run via emulation". When executing docker in terminal, I get crashes in compiling my code now and then. Is there any way to rectify this?

**Comment by sp4ce-cowboy** [comment]
Since you are using a mac, you could try and just install openJDK version 17, as the performance is generally better. And then copy the .vimrc file from the github onto your home directory (and optionally you can set up checkstyle if you wish, the instructions are on one of the pages here)

**Comment by oofpouf** [comment]
Thanks for the suggestion! Have tried to copy the .vimrc file into the home directory, but I got the error ".vimrc" E510: Can't make backup file (add ! to write anyway) when I tried to :wq my other files. Any way to solve this?

**Comment by sp4ce-cowboy** [comment]
> Thanks for the suggestion! Have tried to copy the .vimrc file into the home directory, but I got the error ".vimrc" E510: Can't make backup file (add ! to write anyway)" when I tried to :wq my other files. Any way to solve this?

Right so, this happens when vim doesn't have access to a backup directory. Vim automatically backs up files, and the .vimrc file has a backup location configured with `set backupdir=~/.backup` in one of the lines. You can fix this by going into your home directory and making a backup folder with the command `mkdir .backup` (you have to do this inside terminal as finder doesn't allow you to create hidden folders starting with the `.` symbol) after which you can restart terminal and vim should work fine.
