### ISSUE TITLE
Ungraded Exercise 3

### ISSUE THREAD

**Issue by Suraj2P** [nus-cs2030/2223-s2#825]
Anyone has any idea how to do level 3? How do I trigger the evaluation only when it has reached the end. And how do I check when it has reached the end of pipeline?

**Comment by Yihao2001** [comment]
i stored the previous operation to compare the 2 to see which should be carried out first

**Comment by granolaluvr69** [comment]
First of all, let's go through how we should structure Expr.
In the constructor, you should have:
1. A supplier of the value on the left. (The supplier is used because we want to lazily evaluate the expression.)
2. An optional of an operator. (The optional is used because upon initial creation of the expression, there would be no operator.)
3. A supplier of an optional of an expression of the right. (The supplier is used because we want to lazily evaluate the right hand expression, the optional is used because there will not be a right expression when we first instantiate the expression.)

Secondly, let's take a look at the 3 possible scenarios when evaluating the expression object:

Case 1: The existing operator has a lower precedence (existing executed first) as compared to the incoming operator. (e.g. x * y + ...)
Evaluate the left hand side first, create a new expression with the evaluated left hand side as the new left value, the operator as the incoming operator, and the right hand side as an expression of the incoming value.

Case 2: The existing operator has a higher precedence (incoming executed first) as compared to the incoming operator. (e.g. x + y * ...)
Evaluate the right hand side first, create a new expression with the current left hand side and operator remaining the same, but the right hand side will be where you create an expression of the current right hand expression and recursively call op() on it using the incoming operator and the incoming value.

Case 3: There is no existing operator. (The current expression has been instantiated without being operated on.) (e.g. x + y)
return a new expression with the left hand side remaining the same, the new operator being the incoming operator, and the right hand side expression being the an expression of the incoming value.

Hope I helped!

**Comment by Suraj2P** [comment]
Wow thank you! that helped alot! Can i check does the evaluation have to be done recursively as well? for example when I evaluate the left hand side, do i use the left,operation,right's evaluate? or do i just use left,operation and right?

**Comment by granolaluvr69** [comment]
> Wow thank you! that helped alot! Can i check does the evaluation have to be done recursively as well? for example when I evaluate the left hand side, do i use the left,operation,right's evaluate? or do i just use left,operation and right?
> 
> 

Yes, evaluation has to be done recursively as well.

**Comment by aldensiol** [comment]
> First of all, let's go through how we should structure Expr. In the constructor, you should have:
> 
> 1. A supplier of the value on the left. (The supplier is used because we want to lazily evaluate the expression.)
> 2. An optional of an operator. (The optional is used because upon initial creation of the expression, there would be no operator.)
> 3. A supplier of an optional of an expression of the right. (The supplier is used because we want to lazily evaluate the right hand expression, the optional is used because there will not be a right expression when we first instantiate the expression.)
> 
> Secondly, let's take a look at the 3 possible scenarios when evaluating the expression object:
> 
> Case 1: The existing operator has a lower precedence (existing executed first) as compared to the incoming operator. (e.g. x * y + ...) Evaluate the left hand side first, create a new expression with the evaluated left hand side as the new left value, the operator as the incoming operator, and the right hand side as an expression of the incoming value.
> 
> Case 2: The existing operator has a higher precedence (incoming executed first) as compared to the incoming operator. (e.g. x + y * ...) Evaluate the right hand side first, create a new expression with the current left hand side and operator remaining the same, but the right hand side will be where you create an expression of the current right hand expression and recursively call op() on it using the incoming operator and the incoming value.
> 
> Case 3: There is no existing operator. (The current expression has been instantiated without being operated on.) (e.g. x + y) return a new expression with the left hand side remaining the same, the new operator being the incoming operator, and the right hand side expression being the an expression of the incoming value.
> 
> Hope I helped!

i think i love you granolaluvr69

**Comment by JYeoZS** [comment]
Hi, am still unable to picture how the recursion works. Say we called:

Expr.<Integer>of(2).op(add, 3).op(mul, 4)

How would that look like recursively? Would be helpful if could map out what the left, op, right should look like...

Much thanks. :)

**Comment by calvnleong** [comment]
Hi granolaluvr69, are we supposed to be using the compareTo method to compare the precedence of the operators? Im struggling to find a way to account for the comparison of Optional.empty() and the first operator without using .isEmpty()

**Comment by Suraj2P** [comment]
If im not wrong, you have to use the compareTo method to compare the precedence of the operator. To avoid using .isEmpty() you could possibly use .map(x -> { use an if, else to return a new Expr depending on the precedence using the compareTo}).orElse(if the optional is empty you could return another Expr that you want)

**Comment by e0969533** [comment]
make use of comparable compareTo to compare the precedences

**Comment by Suraj2P** [comment]
Thanks for the help guys! Ill proceed to close this!
