### ISSUE TITLE
Test Case 9_11 - Wait at wrong self-check label

### ISSUE THREAD

**Issue by javianng** [nus-cs2030/2223-s2#837]
# Summary

<img width="762" alt="image" src="https://user-images.githubusercontent.com/65435297/230761940-9750be19-c378-488c-9679-633607634435.png">

There is the mismatch there.

## Description:

The self-check number has been correct for everything except this. I have restricted / prevented other self checkouts apart from checkout k + 1 to take a queue as seen from my code below.

## Code Snippets

```java
// simulator.java

for (int i = numOfServers; i < numOfServers + numOfSelfChecks; i++) { // adding self check
    if (i == numOfServers) {
        serverList = serverList.add(new Server(i, qmax, restTimes, false));
    } else {
        serverList = serverList.add(new Server(i, 0, restTimes, false));
    }
}
```

```java
// server.java

boolean waitAvailability() {
        if (eventsCount <= qmax) {
            return true;
        }
        if (qmax == 0) {
            return false;
        }
        return false;
    }
```
It should not be possible for this to happen .-. where did I mess up :(

**Comment by kcslllll** [comment]
make sure that ur customers are leaving and entering the selfcheckout queue which you are associating your first selfcheckout server with. whenever a selfcheckout server is called, remember to call the first selfcheckout server that has the queue. also, make sure that you are checking the availability of all ur selfcheckout servers, regardless of if they have the selfcheckout queue or not (aka first selfheckout server). ur error seem to be showing that after customer 14 is served by self checkout 4, the new customers that come only care about the availability of selfcheckout 4 and not the other selfcheckouts. even though the other self checkouts do not have their own queue since they all share one queue (first selfcheckout server), each of their available time still matter. hope this helps!

**Comment by javianng** [comment]
I have fixed my issue. I did not adjust the counter when I "transferred" the customer from the main self-checkout to the other self-checkout.
