### ISSUE TITLE
Exercise 4 Maybe or() method 

### ISSUE THREAD

**Issue by aeraeroaer** [nus-cs2030/2223-s2#848]
Hi all, been stuck on this for a while, does anyone know why this error comes up for my or() method? 

<img width="1191" alt="Screenshot 2023-04-11 at 3 21 32 AM" src="https://user-images.githubusercontent.com/122816576/230979937-25cded3e-61bf-492f-9685-b2b3dc7eaef0.png">

Here is how I wrote the or() method: 

Maybe<T> or(Supplier<Maybe<T>> maybe) {
        if (!this.isPresent()) {
            return maybe.get();
        }
        return this;
    }

Thank you very much!

**Comment by UmpoDumpo** [comment]
You need to introduce wildcards in your input supplier, maybe. That's what the 'incompatible type' error means.

**Comment by granolaluvr69** [comment]
Since your supplier is supplying a Maybe<? extends T>, you need to apply PECS to the Maybe<? extends T> as well. To help you better understand, your supplier should be a `Supplier<? extends Maybe<? extends T>>` instead of a `Supplier<Maybe<? extends T>>`, as the Maybe in the angle brackets is also a generic, and they are invariant. (cannot be substituted for one another.)
Hope I helped!

**Comment by haphuong1810103** [comment]
Eventhough for this case, Integer is a subclass of Object, Supplier<Maybe<Integer>> is not a subtype of Supplier<Maybe<Object>>, like the above person mention, you need use <? extends Maybe<? extends T>>

**Comment by aeraeroaer** [comment]
ah i see, the issue is resolved. Thank you very much!
