### ISSUE TITLE
When to type declare in methods? 

### ISSUE THREAD

**Issue by emmannyyy** [nus-cs2030/2223-s2#849]
Hi~ 

I am still very uncertain about when there is a need to type declare for generics in methods. 

![image](https://user-images.githubusercontent.com/122295421/231087970-5dd1892b-012b-41c9-896a-d52385f86d02.png)

One thing I don't understand is why the first static method of() needs type declaration \<T>, but the method below does not need type declaration. 

I am postulating the following:
1. Static methods are not bound to any instantiation of objects, hence the \<T> does not bind to the class's \<T>.
2. Conversely, non-static methods are only callable from instantiated objects, and thus the \<T>s bind automatically to the class's \<T>

Do you guys have an easier way to rmb this? Unfortunately always guessing about these. 

Also, is it true that for constructor methods, there is no need to type declare since we are already initiating a new object, thus it automatically binds to the \<T>? 

Thanks to all the cs gods in advance 

Also just realised that Github converts \<T> into some hidden format, so be sure to use the "\\" escape sequence before writing \<T>

**Comment by aldensiol** [comment]
You have it quite down in 1 and 2, but perhaps to supplement it here is what ChatGPT says : 
Static factory methods typically require type declaration because they create and return instances of the class on which they are defined. Since these methods are static, they cannot access the type parameter of an instance of the class. Therefore, you need to declare the type parameter in the method signature to indicate the type of object that the method will create and return.

As for the method op() below, type declaration is not required because it operates on the same type of object the class represents. Since the type parameter is already known from the declaration of the class, the op() method can access the type parameter explicitly on which they are called.

And similarly for constructor methods, since you have already declared types when writing : "class Expr<T>", your attributes are adopting their types accordingly to T, and there is no new "unknown" type that you'll need to consider
