### ISSUE TITLE
Self ex 4 orElseget method

### ISSUE THREAD

**Issue by AmanDesai34** [nus-cs2030/2223-s2#854]
Hey guys im having an issue with my orElseGet medthod. Attached is my error and screenshots of my code.

<img width="418" alt="Screenshot 2023-04-12 at 12 42 24 PM" src="https://user-images.githubusercontent.com/124550223/231351886-d7cce0a1-9103-4e75-b22e-8bd1831d2b24.png">
<img width="1208" alt="Screenshot 2023-04-12 at 12 42 37 PM" src="https://user-images.githubusercontent.com/124550223/231351918-51a57143-18d8-4e8d-aaf7-1f028bf1c1d0.png">

**Comment by dlyxxx** [comment]
you have to make sure that your supplier can take in anything that extends T because for example, if your original maybe is a maybe Object, then its method, orElseGet can take in anything below Object such as Integer, String, Double etc. but if you just do Supplier<T> it only can take in Object, which is wrong! What helped me with this exercise is looking at the Optional Class in JDK since they are similar!

**Comment by haphuong1810103** [comment]
you should use Supplier<? extends T>

**Comment by AmanDesai34** [comment]
Thank you it was to do with my or method as well
