### ISSUE TITLE
Confused about Lazy Evaluation

### ISSUE THREAD

**Issue by meganyeoyy** [nus-cs2030/2223-s2#865]
Hi, after attempting level 5 of UE3, I realised that I did not quite understand what lazy evaluation means. Can lazy evaluation be done without using stream?
<img width="1078" alt="Screenshot 2023-04-13 at 4 59 07 PM" src="https://user-images.githubusercontent.com/111188123/231709451-598354ac-060d-44e2-b40b-7d5916921e46.png">

**Comment by calvnleong** [comment]
I think lazy evaluation is storing something as a stream, and only getting an output when you use methods like reduce(). For eg, instead of immediately summing up numbers from 1-10 (1+2+...+10), you get a stream that is bounded to a variable. I think prof mentioned in one of his rec that this also helps to prevent stack overflow iirc. Hope this helps

**Comment by sethteo** [comment]
Yup! Like in our Events project, the idea of involving a Supplier for both Customer serve time and Server rest time is a form of lazy evaluation as the supplier is defined BUT not invoked only when it is needed (when we invoke supplier.get())

**Comment by Aron113** [comment]
i think essentially it means that values are only 'produced' from the stream when required. As the notes mention, terminal operations are what invoke the values

**Comment by user23592359** [comment]
Yes, it can. The concept of lazy evaluation can be seen in our discrete event simulator, where we generate the serviceTime and restTime only when we need it, i.e. when the Serve events and Done events are executed. The purpose of this is to make sure that you only retrieve the value when you need it, and it makes your code more efficient and runs faster.
