### ISSUE TITLE
PA 2 Walkthrough error 

### ISSUE THREAD

**Issue by AmanDesai34** [nus-cs2030/2223-s2#905]
# Summary

## Description 
Hey guys i used the walkthrough for this method but am facing an issue. Amy idea why?

## Idea s
Describe the approach used (if applicable)

## Screenshots (if any): 
Insert Images here if necessary
<img width="892" alt="Screenshot 2023-04-19 at 7 02 02 PM" src="https://user-images.githubusercontent.com/124550223/233055297-7fe65deb-6f35-4964-b7fb-353bbb01dd44.png">

**Comment by edmundnwl** [comment]
i don't think Optional has such a method 'or'

**Comment by emmannyyy** [comment]
not 100% sure if this will fix it, but did you import Supplier already? 
![image](https://user-images.githubusercontent.com/122295421/233330507-fdf82f27-729e-40d7-b07a-6afb0540751a.png)

The or() method in Optionals require the use of a supplier. I suspect the reason it's not compiling is because you have not yet imported Suppliers.

**Comment by NeoHW** [comment]
did you have the necessary imports or it could be due to your previous implementation of the 0 params method call

**Comment by aowz** [comment]
Try to import java.util.function.Supplier

**Comment by meganyeoyy** [comment]
my code looks really similar so i think the error might be else where

**Comment by Aron113** [comment]
you could try importing Supplier

**Comment by jacoblimjy** [comment]
Import Supplier should help

**Comment by AmanDesai34** [comment]
Thanks guys got it solved
