### ISSUE TITLE
Pa2 level 5 supplier impl

### ISSUE THREAD

**Issue by tryngmyhardest** [nus-cs2030/2223-s2#918]
Not sure why its not being lazily evaluated... any advice?

<img width="1081" alt="Screenshot 2023-04-20 at 3 32 23 PM" src="https://user-images.githubusercontent.com/127404598/233294354-0953a74e-8195-406f-90cb-ee3513b70e2c.png">
<img width="452" alt="Screenshot 2023-04-20 at 3 32 04 PM" src="https://user-images.githubusercontent.com/127404598/233294411-938dba27-ba5b-4216-b652-44b4cb819352.png">

**Comment by yugan01** [comment]
does ur left(T probGet) and right(T probGet) have any .get() methods inside?

**Comment by leezhanpeng** [comment]
Did you evaluate `pairOf` every time a new `DnC` is created? I assumed from the fact that `(5, 7) evaluated` wasn't printed.

**Comment by emmannyyy** [comment]
I ran into this issue also. Probably something wrong with your left() and right() methods.

In the left() and right() methods, did you first check whether the problem was atomic? 

If you did, that's probably causing the issue, since you would have to first call this.problem.get(). 

I realised that you have to check if the argument problemGet is **not atomic**, and only go to the atomic case **at the end**, if not you would be eagerly evaluating when checking if the problem is atomic.

**Comment by hcyrr** [comment]
experiencing the same prob too! :(

**Comment by lkldev** [comment]
The order does not matter without supplier, prof has made changes to the test case. Do check out the latest announcement on Canvas :)

**Comment by calvnleong** [comment]
you should try to avoid using .get() in left and right methods

**Comment by taugwa** [comment]
rmb that you can only use .get() once per sub problem!

**Comment by meganyeoyy** [comment]
i had the same issue too, and I solved it by ensuring that i used get() in my left() and right() methods. you must use .get() sparingly to avoid run time errors

**Comment by tryngmyhardest** [comment]
thanks all!
