### ISSUE TITLE
AY22/23 S1 Mock Final Q1 Cyclic Dependency question and validity of implementation

### ISSUE THREAD

**Issue by yugan01** [nus-cs2030/2223-s2#919]
In the walkthrough of Q1, to resolve the issue of cyclic dependency, prof introduced a new Interface Notifiable, User then implements this interface and Bot uses this interface.  Instead, I used a parent ParentUser, and User extends ParentUser and Bot uses the ParentUser. I would like to ask if this approach is valid.  

I am also slightly confused about one aspect of cyclic dependency. If I have class A, B, C
B extends A (i.e. B <: A) 
C references A (i.e. in class C, there is a method that takes in A) 
B references C( i.e. in class B, there is a method which takes in C)

I would like to confirm that this does not violate cyclic dependency.

**Comment by Ramanenbh** [comment]
I am not 100% sure but I think this should not violate cyclic dependency as C does not directly depend on B

**Comment by e0970430** [comment]
I think this doesn't violate cyclic dependency because the logic is similar to that of prof's additional interface method; and your code should compile regardless of your User class. You just need to make sure that the join and notify methods (or your equivalents) and other methods that depends on Bot() are only present in your User class and not ParentUser.

**Comment by yugan01** [comment]
ok thank you all!
