### ISSUE TITLE
Ex 4 Maybe or() method

### ISSUE THREAD

**Issue by aeraeroaer** [nus-cs2030/2223-s2#922]
Hi all, Im little lost with the Maybe or() method as I an unsure of how to convert from Maybe<? extends T> back to Maybe<T>

    Maybe<T> or(Supplier<? extends Maybe<? extends T>> maybe) {
        if (!this.isPresent()) {
            return Maybe.<T>of(maybe.get().value);
        }
        return this;
    }
    
why wouldn't this code work?

**Comment by NwaterM** [comment]
The code has the correct logic, not too sure why it's not working, what was the error you're getting? . My logic is the same as yours and it could work, i have a maybe<? extends T> result = supplier.get().  i went on to create a new Maybe<T> by using result.get(). to extract <? extends T> value inside of result.

**Comment by sethteo** [comment]
right now your supplier.get() would return a Maybe<? extends T> but your of() method needs to take in a T, and by calling a get for Maybe<? extends T> you get a ? extends T instead of a T

in order to fix this you can first define a 
Maybe<? extends T> mb = maybe.get()
and then 
return Maybe.<T>of(mb.get())

why you have to do this is because the compiler is unable to predict the data type it is given

**Comment by aeraeroaer** [comment]
i see thank you very much! the issue is now resolved
