### ISSUE TITLE
AY21/22 S2 Q3 why abstract class Maybe?

### ISSUE THREAD

**Issue by jianjiezzz** [nus-cs2030/2223-s2#959]
![image](https://user-images.githubusercontent.com/119864021/233958346-1b89de18-c780-4f69-a15e-255501eea856.png)
why do we have to specifically change to abstract class?

**Comment by aldensiol** [comment]
i believe it has to do with "hiding" the attribute from Maybe's empty(). Since you won't have an input for Maybe.empty(), and you can't use null to assign to empty()'s attribute, you'll need to define it only internally within Maybe.of(thing)'s anonymous inner class.
In contrast, a concrete class will need to have pre-defined attributes (and a constructor for that matter) in which null has to be used
